### ISSUE TITLE
Motion tracking not really working

### ISSUE THREAD

**Issue by marrobHD** [EliasKotlyar/Xiaomi-Dafang-Hacks#1024]
It wont track me. It stays there. Sometime it moves a cm. But that isnt really tracking

**Comment by mariomazon** [comment]
On services -> motion detection, adjust to high (not very high), click configure motion and reboot the camera. Or you can set /system/sdcard/config/motion.conf motion_sensitivity=3 instead of 4, original value. There's a bug not solved referenced at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/195
