### ISSUE TITLE
Artifacts in image stream

### ISSUE THREAD

**Issue by Btje1977** [EliasKotlyar/Xiaomi-Dafang-Hacks#1077]
I use the Xiaomi Xiaofang 1S and have the latest commit added. For viewing I use the RTSP stream.

### Description

Artifacts in the image stream. Sometimes is it a ghosting when having a moving target and sometimes that imagepart where the movement is gets pixxeled. A still standing image or a little movement is ok.

### What did you do to debug the issue

Tried the different settings like vbr and cbr. And tried lower the frames to 20 and even a lower bitrate. This did not help.

**Comment by prankousky** [comment]
I have had similar problems and was just going to ask for help here as well. You should probably post your settings so that it is easier to debug. I **had** a working setup and changed it (d'oh!). I don't remember what it was. The following are my current settings that keep messing up the rtsp stream:

* video username `none`
* video password `none`
* video port `8554`
* video size `1280x720`
* bitrate `800 kbps`
* video format `CBR`
* frame rate `16` per `1` second

I recently tried messing with these settings, because image was a bit blurry. I know the video size is "correct" (anything above this did not work before, either). bitrate 800 should also work, but I am not sure about frame rate and video format. 

I have ghosting as well as pixelation. Currently the bottom part keeps switching between blurrend/pixelated image and green bars/stripes. About a sixth of the picture at the bottom.

**Comment by Btje1977** [comment]
1280*720
Bitrate 2000
Vbr
15 frames

**Comment by arkhub** [comment]
for me it's : 
resolution `1920*1080`
Bitrate `2000`
video format `SMART`
frame rate `15` fps

**Comment by Sungtroll** [comment]
The only mode without any artifacts is the FixedQp, but the video quality from the stream is presenting a far more blurry image than the other settings. Increasing the bitrate i FixedQp doen't seems to improve the video quality or increasing the bitrate. I use the RTSP stream over TCP at 1920x1080 25fps h264 and 8000 kbps PCMU sound. The same artifacts problem appears both in  VLC and in Milestone Xprotect Essentials+ 2019 R2 using the universal driver. For the CBR, VBR and Smart mode I wish there was a way to lower the key frame intervals maybe it could help. Now i just have to use the FixedQp even if the compression is to high and the bitrate is running very low at any bitrate setting up to 8000 mbps. The MJPG stream does not seems to work at eighter VLC or Milestone xprotect.

**Comment by Sungtroll** [comment]
I used xprotect to display video diagnostic overlay at Level 3 setting. What i discovered is that while panning the camera the GOP changes in every streaming mode except for fixedQp. In fixedQp GOP stays at 15 while panning. In CBR, VBR and SMART the GOP increases dramatically while panning the camera or is motion in the view and that is absolutely the opposite of what it should! If there is motion detected the GOP should DECREASE not INCREASE!!!!  Does anyone know how to fix this big bug in dafang hack's RTSP server?

**Comment by Dopeyr** [comment]
Hi, there are `gop`-related properties set at https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/src/ImpEncoder.cpp#L1375 and a few other places. `gopQPStep` and `gopRelation` - but I wouldn't know what to do with them, I'm not a c++ dev :(

**Comment by Sungtroll** [comment]
I changed from connecting to the camera trougt a router to connect directly to the camera from my computers wifi card and now the GOP is normal in any setting. Seems to be a wifi problem. I use Windows 10 and just enabled the mobile hotspot and Connected the camera to the mobile hotspot. It look like that solved the problem for me. There are still a little bit of artifacts while panning sometimes but now it is  almost 90% ok.
