### ISSUE TITLE
How could install the firmware without microsd

### ISSUE THREAD

**Issue by meduar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1144]
HI,

I have been trying to modify directly the firmware of the camera through serial port(putty) but then I realized that it is read only mode. I already made it work with the microsd. so, I just want to know if it is possible to install it withing the camera overwriting the internal os.

is it possible to install the firmware without microsd ?

How could I do it if it is possible?

Thanks.

**Comment by znanev** [comment]
Although it is possible to replace the internal firmware with a custom one in theory, I'm not aware of such successful attempt.

First step will be to setup T20 cross-compile toolchain the way it is described here: https://github.com/anmaped/openfang. The new firmware has to be on a diet (i.e. be small enough) in order to fit in the internal NAND storage. This will severely limit the features that can be included - as is the case with the original firmware, which heavily relies on the cloud.

So from a practical perspective, it is not worth the effort to try to modify the NAND firmware - leave that as is and use any microSD card you can find. SD cards these days are cheap enough to just get one and stuff it permanently into the camera.
