### ISSUE TITLE
Is anyone else having issues with crashing?

### ISSUE THREAD

**Issue by maxiedaniels** [EliasKotlyar/Xiaomi-Dafang-Hacks#1153]
I have a Dafang camera with the latest hacked firmware, but it seems to be crashing after some period of time. When it crashes, I can't seem to connect via ssh, and that rtsp feed is dead.

Any thoughts?

**Comment by tjharman** [comment]
You probably have a flaky SD Card

**Comment by Juna1103** [comment]
You should try UART to camera..

**Comment by maxiedaniels** [comment]
What is UART? I did install uboot, but while that helped stabilize my other camera, this one is crashing very quickly.

**Comment by Juna1103** [comment]
UART, it's a way you can see your cameras bootloader, while the camera on, through putty terminal. 
Maybe get an idea what's happening when your camera crashes.

**Comment by kloknibor** [comment]
I updated yesterday from 05/08/2019 to the latest version, first update failed second was ok but now it crashes after x hours... No connectivity at all anymore.

**Comment by jmtatsch** [comment]
Can you still access the web interface? Check there if ssh process is still running.

**Comment by Lefuneste83** [comment]
I have had a similar issue with an overheating T20 chip.

First issue I had on all Xiaomi cameras (Dafang/Xiaofang) was that I need to activate the swap file in the run.sh in order to avoid losing them after a few hours. My settings bellow. You don''t have to put such a big swap 256 in fine.

## Create a swap file on SD if desired
SWAP=true
SWAPPATH="/system/sdcard/swapfile"
SWAPSIZE=512

Second bigger issue I had with a Xiaofang was that the camera would stop working after a few minutes, the time it took to heat up. It appeared sudenly after several days working properly. I solved the issue by putting a big heatsink on the chip, which confirmed my diagnostic, but I could close the enclosure anymore... I disabled all services but this did not change anything, the runaway heat up was low level. This camera can be quite unreliable if you have a bad one... Lets' hope they bring support to newer T20L chipset which seems to be more efficient.

**Comment by jaredbiehler** [comment]
I'm having the same issue with crashes for the Dafang and the firmware here. Usually this seems to happen shortly after connecting via SSH - I get about 3 - 5 minutes of SSH usage before the OS stops responding. At that point the network connection is simply down; no web server, no SSH, pings are unresponsive (LED is still active, though and the OS does not reboot). After a few minutes the network connection reestablishes itself; then rinse / repeat. If I let the device go without establishing a SSH session, I might get hours of up time so it leads me to believe there's something related to SSH. 

I'm going to try a new SD card and see if that helps, short of that I don't know where to start troubleshooting.

**Comment by coax** [comment]
I enabled the swap file (rename /config/swap.conf.dist to /config/swap.conf, edit file and set SWAP=true) and put a small heatsink onto T20 chip (manufacture date 2019.07) but the freezing issue is still there. Camera just stops responding after 2-3 minutes, blue light stays on. This is my second camera, the first one has no such issues.

![IMG_0906](https://user-images.githubusercontent.com/189817/67769725-48ad6c80-fa55-11e9-922c-069cc64be8da.JPG)

**Comment by Juumm** [comment]
I have the same issue, crash after about 20 hours
I try to enable swap but it does not fix the issue :(

**Comment by coax** [comment]
It seems there are fake Xiaofang cameras on the market. The only logical solution at least.
I have 3 cameras. 2 work perfectly, 1 keeps restarting.
The 2 that work use different font and MAC starts with 44. Otherwise they all look the same and are bought from the same seller on Ali.

![IMG_1228](https://user-images.githubusercontent.com/189817/73593848-903a0d80-4508-11ea-9e32-cd97259963fd.JPG)
