### ISSUE TITLE
I forgot the password

### ISSUE THREAD

**Issue by abeksis** [EliasKotlyar/Xiaomi-Dafang-Hacks#1159]
I forgot my password, and I don't have access. I tried through ssh root username and password ismart12 and I don't have access. Is there a way to log in without the need to redo?

**Comment by Combie81** [comment]
Take the SD Cardiff out, open the file /system/sdcard/config/lighttpd.user

Edit:
# by default root:ismart12
root:all:xxxxxxxxxyourcustompassxxxxxxx

to be:

# by default root:ismart12
root:all:a6564902a687c445cbd80bab194c42d5


This will reset it to default pass of ismart12
________________________________

**Comment by abeksis** [comment]
i do it but i get: 

<img width="1433" alt="Screen Shot 2019-09-08 at 16 22 55" src="https://user-images.githubusercontent.com/10877299/64488837-020d7400-d255-11e9-91a9-e248a3aafaf2.png">

**Comment by abeksis** [comment]
Thanks, done the job

**Comment by Combie81** [comment]
No problem

**Comment by MarkSanders54** [comment]
> Take the SD Card out, open the file /system/sdcard/config/lighttpd.user using notepad++ on pc/mac Edit the contents: # by default root:ismart12 root:all:xxxxxxxxxyourcustompassxxxxxxx To be: # by default root:ismart12 root:all:a6564902a687c445cbd80bab194c42d5 This will reset the root password back to the default of: ismart12

I did something silly, and set the password as:
root:all:a6564**8**02a687c445cbd80bab194c42d5

instead of:
root:all:a6564**9**02a687c445cbd80bab194c42d5

I no longer have physical access to the device because it is setup as a nest cam. I tried putting in "a6564802a687c445cbd80bab194c42d5" as the password with no luck. How is "ismart12" encoded as "a6564902a687c445cbd80bab194c42d5"? Is there anyway to decode the password I have set? I don't see this documented anywhere.
