### ISSUE TITLE
SD Card type, partition and format update in documentation

### ISSUE THREAD

**Issue by uutzinger** [EliasKotlyar/Xiaomi-Dafang-Hacks#1172]
Wyzecam v2, but should be applicable to all models.

### Description

Please update instructions for SD Card partition and formatting with the following information:

Section: "Installation of the microSD bootloader"
Please add: SD Card needs to be fully formatted. It can not be quick formatted.

Section: "Installation of new firmware"
Same SD Card with same file system from previous bootloader update can be used. It must be FAT32 filesystem and it must have been fully formatted either for this installation or the installation of the boot loader.

### Substantiation

I tested several of my SD cards for flashing boot loader and firmware. Some worked and some did not. I also tried ext3 for firmware SD card which does not work. From the one SD card that worked I created an image with Win32 Disk Imager and burned it onto other SD cards that were not booting the firmware but with the new image they did. I used Windows Disk Management Tool and also gparted on Ubuntu to partition and format. I had a 512Mbyte partitioned working SD card. After I was successful in burning a working image onto other cards I tried to increase the partition size to figure out if there is a limit. I realized that in all those attempts I used quick format and I was not able to make the SD cards reliably work beyond the 512 Mbyte partition I already had. On the 512Mb partition card I created a second partition with the remaining free space and it did not negatively impact booting the firmware. I finally tested if using the full disk size in one partition and fully formatting the SD card will reliably work; It worked also with larger partitions. When I created images of the SD cards that did not work I realized that I could not compress the images substantially because they had random data in most blocks. When I compressed the image of the fully partitioned and formatted SD Card that was booting the firmware, I ended up with an archive of only 25 Mbytes although I was covering a 16Gb SD card. That makes me believe that firmware needs to be copied onto a wiped SD card. I used primarily Windows system tools for formatting and partitioning and to edit the configuration files I used Notepad++ on Windows.

I believe the main issue is that most people applying this hack use the SD card that has been used to store images from the original firmware. These cards are usually full of data and when deleting the partition and quick formatting, the card retains data that interferes with the camera software. 
 
### Suggestion

Besides clarifying the instructions, I recommend to provide a minimal SD card image to create a boot loader SD card and a firmware SD card. Users can burn images with Etcher or Win32 disk imager which are often used for raspberry pi projects. I have not yet tested if it is sufficient to simply create a small partition without wiping the unpartitioned space.

**Comment by coax** [comment]
Thumbs up for this tip, I used 4 GB SanDisk SDHC card with (free) [SD Card Formatter](https://www.sdcard.org/downloads/formatter/). Checked "Formatting options: Overwrite format" and it worked. No need to make 512 MB partition.

**Comment by spattinson** [comment]
I'll add my experience, I was trying to use a 64GB card initially with a 100MB partition at the beginning. I did format with erase, it did not work. I Then attach serial to console headers and see that not only the bootloader could not load demo.bin, but also after boot the card could not be mounted, maybe something wrong with it. I found an old 8GB card in a drawer, I did the format with erase a few times, and it would not work, after a few attempts the card died "no medium" error. I went out and bought 2x Verbatim Premium 80MB/s 533x cards. Create 100MB FAT32 partition using Gnome Disks app on Linux and format without erase. It worked fine, on both the two cameras I bought which are Xiaofang 1S 64MB.  I dont know if cards come from the factory with random data or zero'd, presumably they are tested in some way during manufacturing. Flashing is done by the bootloader AFAIK , it is limited in what filesystems it supports, so while you may be able to use ext3 or exfat after linux has started on the camera the bootloader does not have support for those filesystem types. After firmware is flashed, I delete the 100MB partition and create a 16GB FAT32 that fills the card and copy on firmware_mod stuff which works fine, although ext3 may be a better choice due to journalling and the fact that these cams will often be powered off without shutting down properly
