### ISSUE TITLE
MQTT Motion dection does not work

### ISSUE THREAD

**Issue by torbenan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1208]
My MQTT is in general working for the my cameras. (Verified by turn leds on/off)
In Home Assistant the motions sensors is always in the state "off"

binary_sensor.lilledafang_motion_sensor | off
binary_sensor.dafang_motion_sensor | off

I need the motions sensor to be active in order to start an automation for saving a snapshot.

Motion detection is activated on the cameras (verified be the red dot in top/right corner of the picture, when motion is detected).
In the camera control all of these are on:

- Motion dection - on
- rtsp H264 - on
- mqtt server - on
- mqtt control server - on
- motion snapshot - on
- motion mqtt message - on
- motion -mqtt snapshot - on

The cameras are a Xiaomi Dafang and Xiaofang 1S.

**Comment by jmtatsch** [comment]
Connect to your mqtt broker and listen to #.
See if a motion event is posted as expected and on which channel.

**Comment by torbenan** [comment]
What would be the name on the topic?

**Comment by jmtatsch** [comment]
The one you defined in the config?
Don't be lazy. Just follow the instructions.

**Comment by torbenan** [comment]
Is this what you are asking for?
![image](https://user-images.githubusercontent.com/36116874/67373322-b7835500-f57f-11e9-91d5-92b691c45644.png)
![image](https://user-images.githubusercontent.com/36116874/67373359-c538da80-f57f-11e9-922b-bf9dbb1a5dd3.png)

**Comment by jmtatsch** [comment]
The latter almost. 
The motion event should come on the channel Kaelder/LilleDafang/motion
what you see in your last pic ist that the motion detection in general is enabled.
Is publish_mqtt_message in motion.conf enabled?

**Comment by torbenan** [comment]
The channel Kaelder/LilleDafang/motion is empty

this is the content of motion.com
motion_sensitivity=3
motion_indicator_color=2
motion_timeout=-1
motion_tracking=off
motion_detection=on
publish_mqtt_message=true
save_snapshot=true
publish_mqtt_snapshot=true

**Comment by jmtatsch** [comment]
Looks okay. However there is no roi defined which is strange.
Please get a fresh copy from https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/config/motion.conf.dist and make your adjustments.

**Comment by torbenan** [comment]
###################################################################
# edit this file and move it to /system/sdcard/config/motion.conf #
###################################################################

# Enable verbose debug messages to stderr
debug_msg_enable=false

# Configure the motion core parameters:
This is my updated motion.conf. Still no mqqt messages comes through on Kaelder/LilleDafang/motio


region_of_interest=0,0,1280,720
motion_sensitivity=3
motion_indicator_color=2
motion_timeout=-1
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
publish_mqtt_message=true
publish_mqtt_snapshot=true
send_email=false
send_telegram=false
telegram_alert_type=image
send_matrix=false

# General
group_date_pattern="+%d-%m-%Y"
file_date_pattern="+%d-%m-%Y_%H.%M.%S"
video_duration=10

# Record from RTSP (RTSP H264 must be enabled)
# RTSP is alternative for `record_video` function in `detectionOn.sh` - instead of 1s-getimage gets real video.
video_use_rtsp=false
video_rtsp_w=1280
video_rtsp_h=720
video_rtsp_f=15

# Snapshots
save_snapshot=true
save_snapshot_dir=/system/sdcard/DCIM/motion/stills
save_snapshot_attr="0666"
max_snapshot_days=20

# Videos
save_video=false
save_video_dir=/system/sdcard/DCIM/motion/videos
save_video_attr="0666"
max_video_days=10

# Configure FTP snapshots and videos
ftp_snapshot=false
ftp_video=false
ftp_host="ftp.myserver.net"
ftp_port=21
ftp_username="user1"
ftp_password="password2"
ftp_stills_dir="motion/stills"
ftp_videos_dir="motion/videos"

# Configure SMB snapshots and videos
smb_snapshot=false
smb_video=false
smb_share="//DEVICE/SHARE"
smb_username="admin"
smb_password="admin"
smb_stills_path="dafang_camera/stills"
smb_videos_path="dafang_camera/videos"

**Comment by jmtatsch** [comment]
should be on Kaelder/LilleDafang/motion with the n
but the yellow led enables on motion?
also enable debug_msg_enable=true and look inside your log

**Comment by TRSx80** [comment]
I had similar problem on Xiaofang 1S, where motion would indicate (red dot upper right) but the motion event (MQTT, in my case also) would not fire. I spent some time diagnosing MQTT messages on the command line, before I realized that was not the problem at all.

After digging around the forums, I found the solution was to create a swapfile on the SD card, because apparently the Xiaofang (64 MB model) cannot do too many things at once... This got it to work (with one, but not 2 still captures) but that got me started thinking to myself "wow, what a resource constrained device."

I ended up deciding to just feed the RTSP feed into [Motion](https://motion-project.github.io/index.html) on another device (an ODROID-XU4, which I had previously purchased specifically for the purpose) and that seems to be working pretty well so far. Much more options to dial in the motion detection, and it just strikes me as being a much more reliable solution that depending on the camera to do it.

Now, I will say, that I did not spend a lot of time trying to get motion detection working on the Xiaofang. So maybe it is possible. Perhaps others can chime in. Or maybe you figure out how to get it working. I was already planning to use a more robust solution from the outset, so I didn't spend long fiddling with it. I just went straight to setting up Motion (originally I was going to use ZoneMinder).

**Comment by spattinson** [comment]
I was having the same problem as OP. I thought I had swap setup, I didn't. it was lack of memory. I manually ran swapon cmd and enabled it for next boot, I immediately started working, this is what I got in my log before I fixed it, note "returned:-1"
```
:30.709 (1321.385s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1
:34.851 (1325.527s) [ivsMoveDetection]         ImpEncoder.cpp:405      0| Will execute command /system/sdcard/scripts/detectionOn.sh
:34.854 (1325.530s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOn.sh returned:-1 
:34.854 (1325.531s) [ivsMoveDetection]         ImpEncoder.cpp:599      0| Detect !!                              
:36.976 (1327.652s) [ivsMoveDetection]         ImpEncoder.cpp:405      0| Will execute command /system/sdcard/scripts/detectionOff.s
:36.979 (1327.655s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1
```

**Comment by torbenan** [comment]
@jmtatsch _ Sorry for the late answer - i been away for a few days.
**should be on Kaelder/LilleDafang/motion with the n** - that was just a typo from my site

but the yellow led enables on motion? No it doesn't. It can be manually turn on. There is an indication of motion in the picture (red dot)

The debug message has been enable. I see a number of errors like this one
[   13.308503] err sensor read addr = 0xa, value = 0x0
[   13.373934] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   13.381044] i2c i2c-0: --I2C txabrt:
[   13.384731] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK

**Comment by jmtatsch** [comment]
Did you try to enable some swap?

**Comment by torbenan** [comment]
I had enabled the swap file. This solved the problem on the Xiaofang 1S. 
Thanks for the help

**Comment by claud9999** [comment]
Swap to flash memory is a REALLY bad idea, see https://en.wikipedia.org/wiki/Flash_memory#Write_endurance

Not only is flash slow as snot to write (in general, there are exceptions but you pay for that write speed) but you'll eventually end up with blocks that are "worn out" and can no longer be written to. I would love to hear of an alternative to enabling swap to the SD card.

For me, I'm switching to using Motion and the Dafang cams have motion detection turned off. Sure, lots more network traffic, so I'd love to go back to having my cams do the detection.

**Comment by spattinson** [comment]
In general swap to flash is bad. However in our case it allows kernel to move unused data to swap instead of having to keep it memory, in my case it was a few hundred Kb. I dont think this will be paged in and out continously causing flash wear. You pay your money and make your choice, if you buy a 64MB device you have comprimises to make.  I decided to run my cams at 1280x720 I think I can reduce the bootloader allocations for rmem and ispmem then there will be less of a potential problem.

**Comment by Jpsy** [comment]
Just for completeness:
Creating a swap file meanwhile is part of Dafang Hacks. 
You just have to activate it.  Read the FAQ: 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/faq.md
> **What if my scripts in config/userscripts/motiondetection are not executed or mqtt/telegram messages/emails are not sent on motion?**
Your camera probably runs out of memory when processing the motion event. This is likely in cameras with 64MB e.g. the Xiaofang 1s. Try to enable some swap memory by copying swap.conf.dist to swap.conf and setting SWAP=true.
