### ISSUE TITLE
How to setup static ip address?

### ISSUE THREAD

**Issue by daufoo** [EliasKotlyar/Xiaomi-Dafang-Hacks#122]
I have successfully got the cfw up and running. However I would like to setup it up with static ip instead of dhcp, can you let me know how it can be done?

**Comment by shinebar1001** [comment]
Just include something like
 ifconfig wlan0 192.168.180.102 netmask 255.255.255.0
in run.sh

**Comment by hubmon** [comment]
Another option is DHCP Reservation. I prefer this to Static IP. Advantage: manage all IP assignment at the Router. Reduce chances of IP conflict.
This option is usually in the LAN setting of the Router.
IP is reserved based on the MAC of the device.

**Comment by daufoo** [comment]
Thanks guys.

**Comment by 00christian00** [comment]
> ifconfig wlan0 192.168.180.102 netmask 255.255.255.0
Does this still works? I put it just before the end message and it would still use dhcp. 
My router doesn't have dhcp reservation.

**Comment by 00christian00** [comment]
@shinebar1001 
This doesn't seem to work flawlessy. When I first tried it my router would still show a device with the dynamic ip connected, but the static ip was working so I thought it was just something cached that needed to expire.
After less than 1 day, something triggered that reverted the cam to the dynamic ip. I thought the cam crashed since I couldn't connect and saw in the wifi client list the cam with the old dynamic ip, tried to connect with that and it was working.
Rebooted and it was using again the static ip.
I put the command at the end of the run.sh

**Comment by shinebar1001** [comment]
Ah, my mistake: the dhcpd is still running, so it will obviously get a new lease and reconfigure the IP-address after half the lease time or lease time. 
So we need to add
`killall udhcpc` 
before the ifconfig
