### ISSUE TITLE
Can't conect to wifi

### ISSUE THREAD

**Issue by dancer16121983** [EliasKotlyar/Xiaomi-Dafang-Hacks#1224]
I have a DAFANG DF3 cmiit id:2017DP3894
In mihome app working fine.

Can't seem to conect to my AP.

I have a 2.4Ghz network named "FIRENET",  "WPA+WPA2" network type, encription method "TKIP+AES", operation mode "802.11 g/n" and channel bandwidth "20Mhz".

This is my wpa_supplicant.conf file:

**ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
ssid="FIRENET"
# Uncomment to connect to Hidden SSIDs
#scan_ssid=1
key_mgmt=WPA-PSK
pairwise=CCMP TKIP
group=CCMP TKIP WEP104 WEP40
psk="censored"
priority=2
}**

And this is the startup log:

**==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='FIRENET'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Using driver-based off-channel TX
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x825248
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x825248 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: ce:ns:or:ed
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize..
udhcpc: deleting routers
adding dns 212.113.177.241
adding dns 62.169.70.160
adding dns 192.168.1.1
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
lighttpd: 
Startup finished!**

What am i doing wrong?

I instaled the file cfw-1.3.bin from this link before,
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/dafang/cfw-1.3.bin
and followed the instructions line by line...

Any help would be appreciated.

Thank you

**Comment by tERB00** [comment]
Is there any error messages in your router's log?
Try to change encryption method to WPA2-PSK on your router.

**Comment by dancer16121983** [comment]
I have no log option on my router. This is the ISP router and they use a browser based page, with the credentials tied to my contract details. It's very "clean" of options...

I'll try the encryption method WPA2-PSK.

Thanks. Tomorrow i'll try it

**Comment by dancer16121983** [comment]
I checked another page for my router and this is the log for today

Nov 21 19:58:01 2019	Firewall		Firewall Blocked - FW.IPv6 INPUT drop Source 0.0.0.0 Target 0.0.0.0
Nov 21 09:58:01 2019	Firewall		Firewall Blocked - FW.WANATTACK DROP Source 0.0.0.0 Target 0.0.0.0

**Comment by dancer16121983** [comment]
I was messing with this dafang hack at 1:30 PM

**Comment by dancer16121983** [comment]
I only have WPA2 with AES encription

**Comment by Dusty-don** [comment]
I have similar problem with Xiaofang 1s, the starting log is as follows. when i installed the CFW 1.0 the SD card had a time_lapse file but in one of the thread it is mentioned it is ok, so i continue to load the Firmare_mod.
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as 
dropbear: 
Created new certificate for webserver
lighttpd: 
Startup finished!

As said in installtion step3 &4 , i have renamed wpa_suppliant.config.dist to wpa.suppliant.config and edited the details inside for SSID & PSK.

is there anything i am missing or still this issue is because of SD card.
PLease help

**Comment by tERB00** [comment]
@Dusty-don No sensor, no wifi. Looks like you have T20L model and did not installed drivers on your SD card.

**Comment by Dusty-don** [comment]
> @Dusty-don No sensor, no wifi. Looks like you have T20L model and you did not installed drivers on SD card.

@tERB00 I followed the steps instructed in the installation manual
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md
And i opened my Xiaofang 1s and the board says Ingenic T20.
And you mentioned, i did not install the drivers in the SD card, the installation manual doesnt say so. Can you help me how to do it.

**Comment by tERB00** [comment]
@Dusty-don There is no writing on the chip - T20 and T20L are marked the same.
Is your camera's MAC address starts with 78? There is no light sensor inside? If so - most probably you have T20L.
About T20L you can read here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1128

**Comment by Dusty-don** [comment]
@tERB00 My mac address starts with 44

**Comment by tERB00** [comment]
@Dusty-don MAC 44 is not T20L - it is regular T20 and should run CFW no problem. Double check that you have flashed correct CFW for your Xiaofang. If it does not help you need to hook up serial console and see whats going on with it yourself.

**Comment by Dusty-don** [comment]
@tERB00 thanks for your support, i do not have serial console with me now, may be tomorrow i will get one and check. in the mean time, please guide how to get the details after the serial console is connected, because i dont know the ip to do ssh.

**Comment by tERB00** [comment]
@Dusty-don serial console is the same thing as ssh but via serial cable. You'll get in to linux shell and will be able to check system logs and other stuff to troubleshoot wifi.

**Comment by Dusty-don** [comment]
@tERB00 i found out my mistake, i renamed wpa_supplicant.conf.dist to wpa_supplicant.conf and when i checked the estension .dist was still there and finally i created a new file and it worked, but still i am abled to open https://dafang/ . 
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
/system/sdcard/config
file found1
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
update_config=1
Priority group 0
   id=0 ssid='Dusty_Bolt'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x768218
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x768218 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 44:23:7c:4d:11:2e
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: deleting routers
adding dns 192.168.1.1
Initialized gpios
Determined image sensor model as jxf23
dropbear: 
lighttpd: 
Startup finished!

my DHCP clients list has host name Dafang with the mac address of Xiaofang 1s and one more client with a different mac address is registered in DHCP list. Is there anything else i might be doing wrong.

**Comment by tERB00** [comment]
@Dusty-don So, did you tried these is's in your browser? https://dafang/ never works. Remember to put https:// before ip, http:// wont work.

**Comment by Dusty-don** [comment]
@tERB00 worked like a charm. https://dafang/ didnt work. I entered through IP. Thanks a lot for your help.
Lessons: Dont rename wpa_supplicant.conf.dist
May be we should make a note of it. Many comments show people are struck in there.

**Comment by Dusty-don** [comment]
@tERB00 the video is black and white, any quick answer for it or i will browse through the settings

**Comment by dancer16121983** [comment]
Hi. I messed a bit with the conf files...i set defaultgw.conf to 192.168.1.1
Set hostname.conf DF3CFW
Set staticip.conf 192.168.1.176
Set wpa suplicant to:

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
ssid="FIRENET"
#scan_ssid=1
key_mgmt=WPA-PSK
pairwise=CCMP TKIP
group=CCMP TKIP WEP104 WEP40
psk="password"
priority=2
}

Doing ARP -a in CMD i can see the 192.168.1.176 device but with a different MAC....

Why??!?!

**Comment by dancer16121983** [comment]
I'm using WPA2 and still can't connect to http://192.168.1.176/

**Comment by dancer16121983** [comment]
A little update...i changed the static ip to 192.168.1.190 ...it appears with arp -a at CMD line with the correct MAC. maybe it was a ip conflict before
i can ping it sucessfully.
Cant connect through https://192.168.1.190 :/
How can i search for the hostname to see if it has the right name in the network?

**Comment by digiltd** [comment]
> Lessons: Dont rename wpa_supplicant.conf.dist
> May be we should make a note of it. Many comments show people are struck in there.

You can rename it, it is just unfortunate that you were using something (windows?) that didn't rename it correctly to including the extension and hid it instead. I know on mac it asks you if you want to change the extension, and on linux it (to my knowledge) assumes you want to change the extension as well.

But it was a good find, gotchas like that can be tricky to track down :)
