### ISSUE TITLE
BugFix: rtsp-h264 - Status NOT OK

### ISSUE THREAD

**Issue by MasterPIC** [EliasKotlyar/Xiaomi-Dafang-Hacks#125]
@EliasKotlyar 
Please comment the command line
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master &>/dev/null &`
from run.sh to make the management of the scripts used to configure and autostart the services working and reporting the right service status...

**Comment by shinebar1001** [comment]
That is something I couldn't debug until now, but I have an idea: the autoruns are executed before the command you mention is executed. but, in some cases (not always) the v4l2rtsp-server from the run.sh wins the battle and is running instead of the one from the controlscript. So, we should try to add a sleep 1 in the run.sh (or even better an if clause that checks if there is alreade a v4l2rtspserver) - the result should be: If there is already a rtspserver started by one of the autoruns don't try to start another one or make sure it fails (what's the normal behaviour if there is already a v4l2rtspserver)

So we won't make the camera starting no rtsp-server if the scripts are not enabled, what I'd personally like more.

**Comment by MasterPIC** [comment]
Or we could simply move
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master &>/dev/null &
`
into a new optrun,sh and call it from run.sh.

Then when enabling any (v4l2rtsp-server) autoruns the optrun.sh could be renamed to exclude its execution... When enabling obviously its name should be reverted to optrun.sh to make it working on next boot...

**Comment by tthk** [comment]
Fix for Pull Request #203 should fix this issue.

**Comment by shinebar1001** [comment]
as #203 is merged we can close this issue
