### ISSUE TITLE
New rtsp-h264

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#128]
![screenshot_20180226-230749_01](https://user-images.githubusercontent.com/14801148/36698416-1505e2ea-1b4a-11e8-8aab-3d52716f0a35.jpg)
Nightvision with purple color again the same issue? :)
Could you fix it?

**Comment by shinebar1001** [comment]
no problem here - can you please try

>  /system/sdcard/bin/setconf -k n -v 1

**Comment by wojtulab** [comment]
Ok. So that's mean that every restart i should pass this command to disable purple effect?

**Comment by shinebar1001** [comment]
setconf is used to put the v4l2rtspserver in nightvision mode. Obviuosly it isn't working at your place - can you try to reupload it? (transferred by ftp? switched on binary mode? there should be no error message.)

**Comment by wojtulab** [comment]
I downloaded it via curl directly from dafang shell :)

**Comment by shinebar1001** [comment]
I had trouble to download the binaries directly from github because of the redirects. So, setconf is probably a html file? 
Can you please check the size of the file?
`[root@Pucki-Cam:~]# ls -al /system/sdcard/bin/setconf

-rwxr-xr-x    1 root     root          **8964** Feb 17 17:38 /system/sdcard/bin/setconf
`

**Comment by wojtulab** [comment]
ok, repaired.
