### ISSUE TITLE
Unstable connection

### ISSUE THREAD

**Issue by jered6323** [EliasKotlyar/Xiaomi-Dafang-Hacks#1353]
Wyze Cam v2

Using latest build and usb_eth_driver my camera is running over ethernet, but extremely unreliably. Consistently getting over 30 disconnect/no signal errors an hour in Blue Iris (not necessarily every 2 minutes, I just averaged that out after leaving it running for 12 hours - 350 in 12 hours), which is more than I was getting running the Wyze RTSP firmware (around 200 in 12 hours). I did try running it over WiFi for a bit before switching it to ethernet, and the number of disconnects was about the same. What can I do to increase stability?

**Comment by jmtatsch** [comment]
Reduce resolution? Enable swap?

**Comment by jered6323** [comment]
Enabling swap seems to have made a slight improvement - 3 disconnects in the past 10 minutes, which would be 18 per hour if it holds steady. Resolution is currently 1280x720 at 15fps. Would reducing that make a difference?

**Comment by jered6323** [comment]
Update:
12 disconnects in an hour, but it seems to be happening more frequently now.

Also enabled swap on another camera that's on WiFi, getting around 1 disconnect per minute.

**Comment by jmtatsch** [comment]
Did you try a decent power supply?

**Comment by jered6323** [comment]
I'm using the power supply that came with the camera (5v - 1a).

**Comment by jmtatsch** [comment]
Try a different/better one if you have one.

**Comment by jered6323** [comment]
Tried using an iPad charger for the last hour (5v - 2.1a), same problem/amount with disconnects.

**Comment by a5m0** [comment]
Do you have audio on? If so what are your audio settings?

**Comment by fuzzewuzze** [comment]
This is honestly more an issue  of Blue Iris and i've never been able to get anyone there to care, even though i own a license.

One thing you can do to "fix" it is to enable Decoder compatability mode, but then you get artifacts on your image, enough to cause triggers.

How do i know its Blue Iris?  Because i can take VLC and connect to the RTSP stream and run at CBR @ 5000 bitrate and  never drop a frame, i ccan go into the video  stream settings and see it receiving at 5k bitrate @ 1080p.  Meanwhile if i set my image to anything above say 100 bitrate @ Fixed QP i continuously get drops.  

All 4 of my Wyze V2's are fixed with 8db external  antenna and are no more than maybe 20 feet from a wifi extender.

**Comment by timpur** [comment]
@jered6323 
I was looking ever where to try find a solution to my problem. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1796 might fix yours.
