### ISSUE TITLE
Which audio files can it play ?

### ISSUE THREAD

**Issue by sharkoz** [EliasKotlyar/Xiaomi-Dafang-Hacks#14]
Hi

I was playing with the audioplay and tried to play a custom .wav file.

Unfortunately, I only managed to play the original .wav files in chinese, any other custom file I tried did not work.

I tried analyzing the original chinese files, which are sampled at 8000Hz on 16 bits, with a PCM S16 LE codec, but even by providing a wav that matches these settings, I can't make them play correctly. It only makes a quick 'click'.

Any ideas ?

Thanks

**Comment by Shaktohh** [comment]
It seems it's the same as XiaoFang.
The right codec is : mono 16-bit PCM

There is some samples here :  
https://github.com/davidjb/fang-hacks/tree/master/sounds

**Comment by EliasKotlyar** [comment]
The camera is using OSS instead of ALSA. I tried to compile the ossplay-utility , but without a sucess. This utility should be able to play any wav-file

**Comment by EliasKotlyar** [comment]
Okey i got it. I had to compile the a new kernel driver with OSS to make it work. Now it can play any wav file and also can record everything.

Can someone please test?

**Comment by Antimus** [comment]
Ok so I've flashed the firmware, added the files to the card, updates hostname and wifi settings and rebooted it.
Light stays orange, device appears to connect to wifi (router shows the device connected with new hostname) but doesn't get an IP address, nothing works.
I must be doing something wrong here

**Comment by ril3y** [comment]
EliasKotlyar:

Thanks for the work you have done.  I have a question about the audio.  Can you play mp3's etc onto the camera speaker?  I am trying to understand the difference between alsa and oss.  I assume the stock kernel has OSS support compiled in?  Also where is the toolchain you use to compile the kernel modules / apps against.  Thanks!

**Comment by EliasKotlyar** [comment]
Hello ril3y,

That should be possible. You need to compile an audio-decoder such as mpg123, SoX or LAME. As soon as you have a wav-stream, you could pipe it into oss-play which will play the music. 

You can find my toolchain here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software

**Comment by ril3y** [comment]
Elias,
I am actually trying to figure this out for the WYZE (fang).  But thought I would ask about it since I do not have much exp with alsa oss.  I know you can play wav files on it.  I am trying to wrap my head around the process of what is missing.  I mean I have mpg123 compiled but no sound.  I also have asound utils compiled but do not work either.  I suspect its like the DaFang and not using alsa?  Using OSS.  Thanks for the information.  I think I need to compile oss-utils (for the Fang) and test that out.  I really am just lacking the understanding between Soundcard / PCM device and / Codec's.  More Reading.  Thanks again.

**Comment by EliasKotlyar** [comment]
What kind of device is a Wyze(Fang)? Do you have any information? Is it similar to the Dafang? Same Processor(T10/T20)? How do you hacked it? The Dafang couldnt play audio trough OSS because it was lacking support in the kernel module. I had to recompile the module from the toolchain to make it work.

**Comment by ril3y** [comment]
I am just using the serial port header on the PCB.  I should have a remote
ability to jailbreak the WYZE camera too even without the sd card insert
and run method.  Do you have a compile_oss.sh script too like your other
crosscompiled packages?  Helps alot.  I have spent more time cross
compiling then working on my jailbreak.  It seems like every package wants
something different!  Ha!

BTW: this works for the DaFang too.  They use the same XOR key for the
qrcode to configure the network.  Off topic but have you generated your own
FIRMWARE.bin file?  If so what are you "signing" it with.  Bad term, there
is a part of the build process where you input a password like key that
will be used to verify the image.  I am curious about this as I am not sure
where its "checked" before its updated.  Do you have any info on this?

https://codepen.io/ril3y/full/gXyzmO/

Thanks

**Comment by EliasKotlyar** [comment]
Hello ril3y,

I am still not sure what camera you are talking about. Can you provide a datasheet? Does it use the same chipset like the dafang? 

The Dafang is using a Ingenic T20 Chipset.
The original "xiaofang" was using a completely different chip(something with sonix).

Great that you have a serial port on your wyze - try first extracting some informations about the system. It will help others to understand the system and to co-op with you with developing.

Here is a instruction how to dump the firmware: 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md

About your questions:
1. The oss module can be compiled with a simple "make", without any of this "hacks" which i am using to crosscompile other modules. However you need to compile the kernel first. This takes time and you need to configure it well to be able to compile it. If the wyze-camera is based on the same chipset, you can use my "precompiled" modules from the repository:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_mod/driver
Just insmod the modules and you are good to go. 
If its using a different chipset/kernel, you will have to find a proper build system first.

2. I am not signing the "firmware.bin" package. I am generating it with simple tools:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md

If you want to create a Custom Firmware, check the bootloader first. It should provide you with informations. Also: If you already have a "jailbreak", you should be able to flash a custom bootloader and it may contain some "update"-code.

**Comment by ril3y** [comment]
I am not explaining myself correctly.  I have a cross compiler working for
the sonix yes.  I realize these are 2 different CPU's.  I will get you some
more details about the "key" tonight.

**Comment by EliasKotlyar** [comment]
Hello ril3y,

The dafang dont have any signing key for the firmware. You just need to provide a proper file, which can be generated with some open source tools.

About your Problem: If its not using  a similar chipset  there is no way that you would be able to compile the OSS-Module from my repository. Even with your custom-cross compiler. The reason is, that you need to compile it against your kernel, and your kernel will probably have a different audio-driver(the device layer before OSS/Alsa). If i were you, i would try to achieve the following:
1. Collect as much informations as possible about the system. It will help finding solutions for your next problems.
2. Check if the kernel already have a proper sound-driver installed. If so, you can use the userland tools(aplay,oss-play) to play audio without the kernel driver stuff.
2. Try to find a proper toolchain and the original kernel
3. Try to find the configuration of a similar device to configure the kernel. When i was compiling the kernel for the dafang, i found out that there were several devices(named Mango,Bull etc) and the dafang was basically a "bull" device
4. Find out how your original kernel was compiled - does it have alsa support or oss?

**Comment by alibaltschun** [comment]
> Okey i got it. I had to compile the a new kernel driver with OSS to make it work. Now it can play any wav file and also can record everything.
> 
> Can someone please test?

can you give me more information how to do that? iam a newbie, thanks
