### ISSUE TITLE
Xiaomi Xiaofang 1s (t20) bricked?

### ISSUE THREAD

**Issue by ZeroNavigator** [EliasKotlyar/Xiaomi-Dafang-Hacks#1494]
Hello there!
Someone gave me for free this ipcam (Xiaofang 1s) with mac address start from 34:

As he said he tried to hack this camera with xiaofang hacks , edited the uboot and somehow stuck on an Orange light always on and unable to start the camera normally.

I tried to follow many guides in case i will make it work but i am not that familiar with this type of thing.

I have already disassemble the board and soldered the pins on serial port.
Used putty to see what it post, so i post here the log to check if someone knows what is going wrong.

Some times it just reboot after 5 minutes.

-this is the first 5 minute log (as it then go to a reboot)

[Xiaomi xiaofang 1s putty log.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4776552/Xiaomi.xiaofang.1s.putty.log.txt)

following some advises about the 'respond sd to voltage select' issue , i tied to set gpio 48 and gpio 43, rescan mmc, and then clear gpio 48 and 43 with a mmc rescan at the end and boot to see any changes.
This is what it post this time.

[gpio48 & 43 set - clear boot with reset hold.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4776567/gpio48.43.set.-.clear.boot.with.reset.hold.txt)

Still cant identify what is wrong and i need some help here..

Btw this is what bootargs posts (dont know if this helps)
[wrong evn.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4776574/wrong.evn.txt)

My knowledge is very basic so be helpfull on easy steps and it will be really appreciated :)

Waiting for some kind reply..

**Comment by ZeroNavigator** [comment]
anyone?

**Comment by tachang** [comment]
Why does it say:
```
Trying to mount SDCard...
Trying to mount SDCard...
Trying to mount SDCard...
Trying to mount SDCard...
Trying to mount SDCard...
Trying to mount SDCard...
Trying to mount SDCard...
Couldnt mount, starting normal...
```

**Comment by tachang** [comment]
It seems like it is just booting the default firmware no? 5.6.2.43
And not necessarily anything from your SDCard.

**Comment by ZeroNavigator** [comment]
even though.. is there any boot error ? since it is not booting properly do you identify the reason?

**Comment by tachang** [comment]
My understanding is that you're successfully using a new bootloader:

```
Bootloader-Version: Dafanghacks v1
```

`uboot` is trying o boot from SD card.

```
Running SDupdate....
Card did not respond to voltage select!
```

So is your sdcard inserted properly? Is it formatted FAT32? Is the microsd card bad? Try buying a new one or use something you know works.

**Comment by ZeroNavigator** [comment]
dont really know if there is in fact a 100% error on the sd card ,but in any way the camera should boot even without an sd card as the sd is only used for recording..

**Comment by tachang** [comment]
So someone possibly updated the uboot but the bootloader is doing something other than what a the normal one does.
I would reflash the bootloader (very very very carefully) from uboot itself to something stock. Once you do that you'll have a working stock camera.

**Comment by tachang** [comment]
These are some of my notes for working with uboot and generally reading in a new bootloader.



# Manually flashing the bootloader

Picked a location in RAM: 0x80600000

`sf probe`


Read in the new bootloader from the sdcard to RAM
`ext4load mmc 0:1 0x80600000 /bootloader/u-boot-lzo-with-spl.bin`
`fatload mmc 0:1 0x80600000 /u-boot-lzo-with-spl.bin`

# Don't erase the current bootloader until you are sure you can load it into memory
`sf erase 0 0x40000`


Write from RAM to the NAND
`sf write 0x80600000 0 0x40000`

Read the new bootloader into RAM
sf read 0x80600000 0 0x40000

Print out the first 30 bytes to make sure it looks like a bootloader.

```
# md.b 0x80600000 30
80600000: 06 05 04 03 02 55 aa 55 aa 64 00 00 0c 39 00 00    .....U.U.d...9..
80600010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
80600020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
```

Flashing the bootloader when all you have is serial

I had to flash it because I messed up the GPIO pins and had no access to USB ethernet or sdcard (since I couldn't enable the MMC subsystem). Ended up using the `ymodem` protocol.

Using picocom


`CTRL+A, S` - Used to send a file

```
isvp_t20# loady          
## Ready for binary (ymodem) download to 0x82000000 at 115200 bps...
C
*** file: /tmp/u-boot-lzo-with-spl.bin
$ sz -vv /tmp/u-boot-lzo-with-spl.bin
Sending: u-boot-lzo-with-spl.bin
Ymodem sectors/kbytes sent:  17/ 2k

Transfer complete

*** exit status: 0 ***
## Total Size      = 0x00034be2 = 216034 Bytes
```

isvp_t20# md.b 0x82000000 30
82000000: 06 05 04 03 02 55 aa 55 aa 1c 00 00 0c 39 00 00    .....U.U.....9..
82000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
82000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

isvp_t20# sf erase 0 0x40000
SF: 262144 bytes @ 0x0 Erased: OK
--->erase spend 750 ms
isvp_t20# sf write 0x82000000 0 0x40000
SF: 262144 bytes @ 0x0 Written: OK
--->write spend 401 ms
isvp_t20# sf read 0x80600000 0 0x40000
SF: 262144 bytes @ 0x0 Read: OK
--->read spend 41 ms
isvp_t20# md.b 0x80600000 30
80600000: 06 05 04 03 02 55 aa 55 aa 1c 00 00 0c 39 00 00    .....U.U.....9..
80600010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
80600020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
isvp_t20#
