### ISSUE TITLE
Preventing other users to write to my Telegram Bot

### ISSUE THREAD

**Issue by abbarubababba123** [EliasKotlyar/Xiaomi-Dafang-Hacks#1557]
Hi! First of all, thanks for the amazing hack and long-term support you're providing.
It's been a while I've done this hack, but only in the last few weeks I noticed an incrementing number of people trying to write to my bot messages: of course they cannot do anything (i.e. receiving photos), but it's pretty annoying.
Currently I'm writing messages directly to my bot, which is not in any Telegram group (I've disable this option).
Is there any code I can add to prevent other Telegram IDs (except from mine) to write to my bot?
Thanks folks!

**Comment by fundef1** [comment]
(I run my own script for telegram, but IMO this is more telegram related than dafang and holds for the built-in script as well)

Essentially No: Telegram bots are public by design - anyone can start a chat with any bot.
How your bot responds to that chat is under your control.

I run my bots in (super)groups and theb ot automatiically leaves all non-matching group-IDs.
So, it could be that someone is spamming my bots, but I never even notice it on my end. 

So I am curious how do you 'notice' it? (If it's in your telegram client than I don't understand how you've set it up.)

**Comment by abbarubababba123** [comment]
Hi, thanks for replying! Basically I interact directly with my bot, I didn't put it in any group.
When someone try to write to that bot I receive: 

```
Received message from not authrized chat: -X
User: Y
Message: Z
```

And that's pretty annoying. Can you please tell me what's your setup instead? :)
