### ISSUE TITLE
Video recorded by motion always start green

### ISSUE THREAD

**Issue by alexandrepossebom** [EliasKotlyar/Xiaomi-Dafang-Hacks#1565]
Hi my Wyze Cam V2 have problem when recording videos, the videos starts green some seconds and after a while sometimes  its turns normal.

Do you guys have suggestions to fix this issue?

I am using the stable branch 5c07eb3.

### Description

Videos recorded by motion always start green.

I changed video setting but no luck.

### What did you do to debug the issue

I have lot of this error in my dmesg:

```
[   13.338607] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   13.345758] i2c i2c-0: --I2C txabrt:
[   13.349466] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   13.356077] error: sensor_read,172 ret = -5
[   13.360411]  sensor_read: addr=0xa value = 0x0
[   13.365026] err sensor read addr = 0xa, value = 0x0
```
### Evidence

[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/5158564/startup.log)

<img width="478" alt="Captura de Tela 2020-09-01 às 17 13 26" src="https://user-images.githubusercontent.com/91110/91901337-75826f80-ec76-11ea-8434-a20a92f4645b.png">

**Comment by eerorossi** [comment]
I noticed the same issue with Xiaomi Dafang. Motion videos always start green and only after a few seconds turn to normal.
![green](https://user-images.githubusercontent.com/46249185/92469496-90f0fb80-f1dd-11ea-8203-e284c13b5502.JPG)

**Comment by alexandrepossebom** [comment]
> I noticed the same issue with Xiaomi Dafang. Motion videos always start green and only after a few seconds turn to normal.
> ![green](https://user-images.githubusercontent.com/46249185/92469496-90f0fb80-f1dd-11ea-8203-e284c13b5502.JPG)

It's Wyze Cam V2 too?

**Comment by icebrian** [comment]
Try changing Video configuration, lower bitrate or changing format to see if it still persists. Just saying this as I also noticed with CBR format and a high bitrate that that would also happen when viewing video feed.

**Comment by eerorossi** [comment]
I changed 'video_use_rtsp=false'. Now the video is kind a series of stills, which is good enough fo me.

**Comment by alexandrepossebom** [comment]
Its works for me too but it's without audio and only have 1 fps

**Comment by emiliogon** [comment]
I also experience this with 100% of the automatic motion recordings.  My bar for performance with recordings is "would it pass as evidence in court?"  I seriously doubt these would pass.

![Screen Shot 2020-10-11 at 10 53 13](https://user-images.githubusercontent.com/21245821/95681857-1afefc00-0bb0-11eb-997f-4e10e50e65e7.png)

Judging by what I've seen from MPEG performance before, all this feature does is send some of the video stream to a file.  This is not how MPEG files work: the green area is the codec having to start decoding the image from scratch with no information from the prior frames (some video players won't even open the files).  Proper MPEG files have data that properly describes the first frame.

I have tried a variety of settings and _nothing_ actually fixes this issue.  **Reducing the bitrate or video size does not fix the issue**, it just reduces the time needed to determine a full frame.  Reducing quality also starts to fail the "evidence in court" test (as may recording to a separate server, as neither RTSP nor wi-fi are flawless).

Because of this, motion recording is not a full feature.  To be a proper feature, one that produces usable files, files must either be recorded properly (not just sending a data stream to disk) or they must be post-processed after recording.
