### ISSUE TITLE
Modify recording control script to save video in segments

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#1635]
I am using Xiaomi-Dafang-Hack on  Xiaofang 1S T20 camera.

Current recording script works fine (well, it doesn't insert date into filename) but appears to record video into one  file.   I would like to use the recording script to record continuously (24 hours a day), but save video in segments of 1 minute, 5 minutes, 10 minutes, etc...

Is there a script currently available which already does this?  If not, any guidance on modifying the recording script to do it?

**Comment by benru** [comment]
There currently isn't a way to do this, but I was planning on adding this feature myself. For my use case I only need the file to be split into segments before it hits 4GB because my SD card does not support files bigger than 4GB.

If it splits the recording into multiple segments based on time, how should the files be named? Should it name the file based on the new start of the segment, or should it be the start of the recording with a part number e.g. "REC_12-00-00_part3.h264"?

**Comment by SomebodySysop** [comment]
Is it possible for each segment to have the time that it is recorded?  Something like:

REC_20201208-0100
REC_20201208-0215
...

etc...
