### ISSUE TITLE
Wyze v2: Dafang-hacks switch to AP-Mode if wifi is unavailable: Security risk ?

### ISSUE THREAD

**Issue by cybdn** [EliasKotlyar/Xiaomi-Dafang-Hacks#1739]
Hi there! 

Wyze v2, last stable commit

When i deactivated my wifi network and rebooted the 2 Wyze v2 cam, they switched to AP-Mode. A wifi network named Dafang-(mac-adress) was created ... 
I was then able to connect to it using the default password ismart12
This is bad... As anyone in the wifi range can connect to the cameras, it's a risk that I believe should be stated or that "AP Mode switching" when Wifi is unavailable should be optionnal.

I reactivated my wifi network and rebooted the 2 cameras. The 2 cameras connected to the wifi and the Dafang wifi was deactivated...

Nowhere in the web interface I can find something relating to that. Few things I think could be responsible for that behavior 
First, is something called miio... The configuration can be found:
/system/etc/miio/device.conf
Also, you can check the sh file that use that configuration file:
/system/etc/miio_client/wifi_start.sh

Also, that AP mode could be from that an hostapd configuration:
/usr/share/hostapd_wpa2.conf
Used in correlation with
udhcpd_wpa2.conf to assign dhcp address and dhcp options...

**Comment by hugalafutro** [comment]
you can change the password for that AP in the same ui screen where you set password for connecting cam to wifi
Cog / System / Network / Access Point Password

**Comment by cybdn** [comment]
you are right! I didn't saw the network tab.
The access point name is also there.
I'm sorry.

I believe that if I leave the name empty, it will not start the AP in case of unavailable wifi ?

**Comment by hugalafutro** [comment]
I'm not really sure about that. I just use strong password and forget about it. Think about the AP as fail-safe for cams in hard to reach places. If your is easily accessible just give leaving it blank a try. If that doesn't work you could try messing with values in `/system/sdcard/config/hostapd.conf` and empty some of those if you absolutely have to disable the AP.

**Comment by joshuahaertel** [comment]
For anyone else who stumbles on this issue while looking for a way to prevent a camera from going into access point mode, I looked through the code today and I believe the simplest thing you can do is set `connect_timeout=inf` in the `/system/sdcard/config/wifi.conf`. Example using the conf.dist:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/e7c84ddf59101d650562ef1cfc4bec64ccae6dd2/firmware_mod/config/wifi.conf.dist#L1
This is will prevent the wpa watchdog from hitting the timeout, killing the wpa process and starting the access point mode https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/116c1ad53d04933ac91842d981d17015555a584f/firmware_mod/scripts/wifi.sh#L146-L154
This is desirable for me because my wifi network name is hidden and it looks like the way the polling currently works, it will never switch back.
