### ISSUE TITLE
Time resets to epoch after reboot if cam blocked from internet

### ISSUE THREAD

**Issue by bverkron** [EliasKotlyar/Xiaomi-Dafang-Hacks#1750]
* exact camera hardware: Wyze v2
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: b6a93e9cf5130251f596e66aabfe0d34c43a0828

### Description
If the cam is rebooted while blocked from the internet the time gets reset to the epoch date.
I would expect it to retain the time internally and sync with the ntp server periodically to correct drift.
I would not expect it to lose it's time setting entirely on a reboot (or any other time) if it cannot reach the ntp server

### What did you do to debug the issue

As soon as I unblock the cam from the internet and re-save the Time settings it updates to the correct time from the ntp server.
If I reboot with the unblocked from the internet the time is held as expected.
If I block the cam from the internet and reboot the time gets reset to the epoc

**Comment by c---** [comment]
hwclock is installed but reports `can't open '/dev/misc/rtc': No such file or directory` so I assume it has no real time clock that could survive a reboot.

I have an internal NTP server that the cameras use without needing access to the Internet.

Since you like hacking cameras do you happen to run OpenWRT/DD-WRT on your router? Easy to set up a NTP server there. Speaking of which, most routers lose their time when they reboot too, along with cable modems and other such devices. Even the ubiquitous Raspberry Pi doesn't have a RTC.

**Comment by bverkron** [comment]
Interesting. I am using an EdgeRouter X and it seems it may be possible to set it up as an ntp server, but not sure if Dafang will pick it up from that. https://bneijt.nl/blog/add-ntp-server-address-in-dhcp-response-of-edgerouter/
