### ISSUE TITLE
No Audio in Home Assistant (Wyze V2)

### ISSUE THREAD

**Issue by broyuken** [EliasKotlyar/Xiaomi-Dafang-Hacks#1757]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
Wyze Cam V2

### Description
I just installed the defang hack on my wyze v2 and it seems to be working great so far, the only issue so far is that I can't get audio to work in Home Assistant. Audio stream works via VLC, but when I put it in HA the volume icon is crossed out. This is my config

  - platform: generic
    stream_source: rtsp://admin:password@x.x.x.x:8554/unicast
    still_image_url: https://x.x.x.x/cgi-bin/currentpic.cgi
    username: !secret defang_username
    password: !secret defang_password
    authentication: basic
    verify_ssl: false
    name: Garage Defang

![image](https://user-images.githubusercontent.com/1593391/125124613-635b3400-e0c6-11eb-9e2d-fafb3366bea3.png)

I've also tried ffmpeg in HA, as well as changing the audio from mp3 to PCMU. Nothing seems to work. Any ideas on how to get audio in the RTSP stream into HA?

**Comment by broyuken** [comment]
Has anyone else run into something similar?

**Comment by towerofpower256** [comment]
I went down the same rabbit-hole, and it turns out that Home Assistant isn't great for using cameras with audio.

In the below link, shanem goes on to say that HA is not an NVR solution, and isn't great when you try to use it like one.
https://community.home-assistant.io/t/rtsp-camera-and-audio/111106/9

In the below link, wmaker says "HA (As Far as I Know) does not support getting a camera’s audio stream".
https://community.home-assistant.io/t/rtsp-cameras-with-no-sound/183864

A couple of discussions recommend using something other than Home Assistant for NVR-type activities, such as MotionEye.
https://github.com/ccrisan/motioneye

**Comment by broyuken** [comment]
motioneye doesn't support audio either

**Comment by realthk** [comment]
I also have similar problem with my Dafang camera: no audio att all (though the speaker icon is grayed out, not crossed), no matter what audio setting I tried:
![dafang speaker](https://user-images.githubusercontent.com/5654575/132142071-1b24eef3-b3e7-4d58-af53-03c6b87dcff4.png)

OK, HA is not great for this purpose, but my Reolink RLC-410W camera works fine with audio! (with the same rtsp setup)

Checking the audio stream of the Reolink, it is 32 kHz AAC, which I cannot set in this Dafang firmware. Could it be possible somehow to set AAC audio in this fw?

**Comment by Rowleys** [comment]
Hi, was there any update here, I have the same problem, No sound with RTMP as well
