### ISSUE TITLE
timelapse recording?

### ISSUE THREAD

**Issue by herrxyz** [EliasKotlyar/Xiaomi-Dafang-Hacks#182]
hey guys,
I'm looking for a possibility to do timelapse-recordings to sd-card.
if it's already possible, it would be great to add it to FAQ

**Comment by zanthorn** [comment]
I have not seen a way to do that just yet but would love to save the image on an interval to the SD Card

**Comment by goermezer** [comment]
you can create a jpg by:

/system/sdcard/bin/getimage > /system/sdcard/nas/Kameras/camera2/`date +%d-%m-%Y_%H.%M.%S`.jpg

This implemented into motion detection script (see #178) should work.

**Comment by goermezer** [comment]
Here is what I did to save JPGs with motion detection:

The configuration (region and sensitivity)  is done through the HTML pages. But if you need to trigger something, you need to create two scripts, which will be executed whenever motion is detected or motion ends:

Motion detected executes /system/sdcard/scripts/detectionOn.sh
Motion end executes         /system/sdcard/scripts/detectionOff.sh

For example you can capture a JPG to SDCard whenever motion is detected. Simply create the file /system/sdcard/scripts/detectionOn.sh and put the following:

```
#!/bin/sh

filename=`date +%d-%m-%Y_%H.%M.%S`.jpg
/system/sdcard/bin/getimage > /system/sdcard/$filename &

```
Make the file executable. Otherwise it will not be executed:
`chmod 755 /system/sdcard/scripts/detectionOn.sh`

**Comment by herrxyz** [comment]
thanks a lot, it works great 👍 
tried to make a script to start it from browser
```
#!/bin/sh

status()
{  run_timelapse=$(cat /run/timelapse.status)
   if [ "$run_timelapse" == true ]; then
   echo "started"
   fi
}

running()
{
  run_timelapse=$(cat /run/timelapse.status)
  while $run_timelapse; do
	run_timelapse=$(cat /run/timelapse.status)
	/system/sdcard/bin/getimage > /system/sdcard/DCIM/`date +%d-%m-%Y_%H.%M.%S`.jpg &
	# /system/sdcard/bin/getimage > /system/sdcard/DCIM/`date +%d-%m-%Y_%H.%M.%S`.jpg  &>/dev/null ##change me
	echo "created img " `date +%d-%m-%Y_%H.%M.%S`.jpg
	sleep 10s
  done
}


start()
{
  LOG=/dev/null
  echo "Starting timelapse"
  echo true > /run/timelapse.status
  running &
  PID=$!
  echo $PID
}

stop()
{
  echo false > /run/timelapse.status
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
```
unfortunately, when I start it via webinterface, the interface does not reload, instead the webinterface hangs. after removing parameters manually and reloading the interface work as expected (script starts taking pictures after pressing "start")
if someone has a suggestion to fix this, I would send a pull-request

**Comment by th0ma5w** [comment]
Not sure about issue #189 but pull request #263 fixes some of the issues around start and stop not working for the timelapse control script.

**Comment by jmtatsch** [comment]
Feature implemented and merged please reopen if still an issue.
