### ISSUE TITLE
Segmentation fault when trying to to a video record

### ISSUE THREAD

**Issue by markwain** [EliasKotlyar/Xiaomi-Dafang-Hacks#189]
Hi!
So ... I was trying to record a video ... executed this command from the doc
`/system/sdcard/bin/h264Snap > /system/sdcard/video.h264`
 and got following error
> Segmentation fault

**Comment by goermezer** [comment]
I had this too. It turned out, that you can not start a second stream while the process v4l2rtspserver-master was already running. If you stop that instance, it should work. But for me the quality was really bad compared to v4l2rtspserver-master.

I miss a feature to write the stream directly to sdcard or a NAS whenever motion happens. There is an avconv binary which worked for me, but it was too slow to execute it from the motion detection scripts.

**Comment by helio58** [comment]
@goermezer how did you solve the recording ?

**Comment by jmtatsch** [comment]
I can confirm that it is only segfaulting if v4l2rtspserver-master is running.

**Comment by goermezer** [comment]
@helio58 see https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/182

**Comment by jmtatsch** [comment]
I guess we should be able to record with avconf while rtspserver is running see #106

**Comment by jmtatsch** [comment]
Closing this in favour of #106. Please continue the discussion there.
