### ISSUE TITLE
Static IP Assignment

### ISSUE THREAD

**Issue by coyote20000** [EliasKotlyar/Xiaomi-Dafang-Hacks#198]
Please post a sample of run.sh modified for static IP assignment.
I have seen the Wiki page for static IP but it does not assign any IP when run.sh is modified for my network.

Thanks,
Dave

**Comment by tthk** [comment]
I have my camera's MAC address set in my DHCP router to be given a fixed IP address.  This is effectively a static IP as long as the DHCP server is working on your network, and allows more centralized management of IP addresses.

**Comment by jeroenkl** [comment]
I used the info in the Wiki page and is working fine expect the time settings.
The time/date is Wed Dec 31 23:01:30 GMT 1969 
Who can assist/advice?

**Comment by jeroenkl** [comment]
possible...
But I tried also to use the NTP server 192.168.2.254 (my router)

**Comment by jeroenkl** [comment]
Ok, with static IP set according the Wiki, no route to the gateway possible. NTP not resolved.
Used now my NAS as NTP server, works great.

**Comment by shinebar1001** [comment]
Yep. You have to add a route like
`route add default gw 192.168.1.1`
To enable DNS you have to enter the correct DNS-Server in resolv.conf like
echo "nameserver 192.168.1.1" > /tmp/resolv.conf

**Comment by alfem** [comment]
I think the above methods are now obsolete, aren't they?

I installed the latest update and discover some very useful files in /system/sdcard/config. In order to switch from dhcp to fixed ip, just copy:

defaultgw.conf.dist -> defaultgw.conf
staticip.conf.dist -> staticip.conf
resolv.conf.dist -> resolv.conf

Edit these files, and set up your fixed ip, gateway and dns. Reboot, and enjoy!

**Comment by mbonesi** [comment]
I did as per the above but no luck with DNS resolving.
after I log in as root I still get errror on nslookup calls even querying 'www.google.com'
