### ISSUE TITLE
avconv problem - Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by codewizer** [EliasKotlyar/Xiaomi-Dafang-Hacks#215]
Hi,

i really need help. the cam is currently running on rtsp-h264, and I have a problem recording a video using avconv command below through putty: 
`/system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://192.168.1.110:8554/unicast -vcodec copy -c:a aac -strict experimental -t 10 /system/sdcard/motion/video/test1.mov`

> Input #0, rtsp, from 'rtsp://192.168.1.110:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2017.10.28
    comment         : LIVE555 Streaming Media v2017.10.28
  Duration: 00:00:20.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: [0][0][0][0] / 0x0000
      none
      90k tbn
Output #0, mov, to '/system/sdcard/motion/video/test1.mov':
Output file #0 does not contain any stream

> 

It always say "Output file#0 does not contain any stream". and there's no video file generated.

**Comment by Psudonico** [comment]
Have you started rtsp-mjpeg script?

**Comment by codewizer** [comment]
i'm on rtsp-h264

**Comment by Psudonico** [comment]
try using rtsp-mjpeg

**Comment by codewizer** [comment]
> try using rtsp-mjpeg
it worked. but how can i record a video while on rtsp-h264?

**Comment by Psudonico** [comment]
I think you can't in this moment.
You shuld try to:

- stop rtsp-h264
- capture
- start rtsp-h264

**Comment by anup-d** [comment]
Strange, @Psudonico. Why do you say rtsp-h264 cannot be recorded? It's working fine on my end.

Using this command:
/system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://192.168.1.105:8554/unicast -vcodec copy -an -t 60 /system/sdcard/motion/video/test1.mp4

The issue is with weak CPU of the Dafang. You can only successfully record in h264 format if you lower the bitrate of the video feed significantly using: 
/system/sdcard/bin/setconf -k b -v 1000

Set a value between 100 and 1000, disable motion detection and it works flawlessly. With motion detection on and/or high bitrate, the rtsp server crashes and recording video is no longer possible. That's when you get the blank file with no video.

rtsp-mjpeg is much less demanding on the CPU and that's why you can record without any compromises.

**Comment by Psudonico** [comment]
Hi @anup-d,
I said that not work because in my case CPU crash even if I lower bitrate to 500.
I can't disable motion detection for security reasons.
I'am using dafang with camcloud service.

**Comment by jmtatsch** [comment]
You are using the Xiaomi cloud software and try to record with avconv? I am afraid that is not possible.

**Comment by Psudonico** [comment]
Hi @jmtatsch ,
I am using [https://www.camcloud.com](https://www.camcloud.com)

**Comment by jmtatsch** [comment]
If you use camcloud, why local motion detection and recording?

**Comment by Psudonico** [comment]
@jmtatsch 
I do not understand your question,
when the webcam detects a movement it sends a movie of 20 sec. at camcloud.com using FTP.

**Comment by jmtatsch** [comment]
Let's bundle all recording related discussions in #106.
