### ISSUE TITLE
No audio in stream

### ISSUE THREAD

**Issue by tyronevdm** [EliasKotlyar/Xiaomi-Dafang-Hacks#234]
Hi just installed custom fireware. Stream video working great but have no audio , when I click 'test audio' I can hear the Chinese voice say something and it's clear. Anyone know how I can go about debugging this problem or something I need to set ?

**Comment by anup-d** [comment]
Same problem here. This issue has been brought up before multiple times already. Hope somebody has a solution.

**Comment by nik0** [comment]
With which tool do you listen the audio ?
What are the log of the v4l2rtspserver-master process?
It is working for me on iPhone ....

**Comment by anup-d** [comment]
@nik0 Using VLC player to stream the rtsp live. Getting no audio. DId you tweak something or using a special app?

**Comment by nik0** [comment]
Does VLC say something about the audoi stream ? type, number of received packet (codec information/statistic)
Did you do the "trick" mention there https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/178#event-1559702675 by goermezer ? 
This increase the available memory
or did you try to lower the resolution of the video ?

**Comment by anup-d** [comment]
VLC is only providing this much info:
https://i.imgur.com/yuTRptl.png

No, the video resolution is 720p and I haven't changed it. I just experimented by making a loud noise near the speaker/microphone grill of the camera and I can hear the noise on the VLC player if I press my ear against the phone. So this seems to be a volume sensitivity issue of the Dafang's microphone. Is there any way to ramp up the sensitivity so that it can pick up sound from a distance?

Just FYI, even the test option that plays an audio on the camera's speakers plays it in low volume whereas the original Dafang software was very loud. Once again, this points towards a volume issue which can possibly be fixed by tweaking some parameters somewhere.

Any help would be greatly appreciated.

**Comment by anup-d** [comment]
Thanks. It may have improved the audio by 1% but it's still far from usable. I think the Dafang's microphone is terrible. Only when you speak something loudly by pressing your mouth against the camera, only then can you hear what is being said.

If there are other improvement you can bring, I would love to test it out but I was wondering if its possible to attach an external mic to the Dafang as the built-in mic was horrible even before I installed the hack.

**Comment by nik0** [comment]
Sorry audioplay is not involved here, my bad ...
But you can play around these tool:
`/system/sdcard/bin/ossplay -g 1000 /usr/share/notify/CN/speaker.wav` 1000 is the gain (around max)
There is also
` /system/sdcard/bin/ossrecord -v -g 1000 /tmp/sample.wav` that you can replay with ossplay


AND
you can test this server (I set the mp3 gain to the max), if it is better I will make a version with some configuration
[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1929334/v4l2rtspserver-master.zip)

**Comment by tyronevdm** [comment]
@niko how do I install this zip ?

**Comment by anup-d** [comment]
With the new v4l2rtspserver-master, the sound is much more audible now but it also introduces a constant static background noise due to the high gain which is not only annoying but also drowns out a lot of the actual sound that we want to hear.

**Comment by nik0** [comment]
@tyronevdm copy the file on your sdcard (replace the existing) it should be in bin folder
to get the log you have to start manually the process

@anup-d I set the gain to the maximum (when encoding), I agree that it is not the ideal (I didn't succeed changing it at low level.
Next steps: I will try playing around then encoder to see there is a better encoder filter
and see if the gain can be set at lower level ...

Nik0

**Comment by anup-d** [comment]
Thanks @nik0. Appreciate the effort on your part.

**Comment by goermezer** [comment]
Since the last couple of days I have this audio issue too. But only, when rtspserver is started from services. Then also the whole system slows down. Often then VLC can not play the stream at all.

If I start rtspserver from the shell, everything is ok. Therefore I went back and added this to run.sh, which seems to be a workaround for me at the moment:

`/system/sdcard/bin/v4l2rtspserver-master -W 1600 -H 900 &`

**Comment by sanderdh** [comment]
I also have no (clear) audio stream, video plays fine. Even if I run v4l2rtspserver-master -W 640 -H 480 I still get this audio issue. If I hit the audio test button I can hear some chirps but nothing that could be understood. I am trying to play the stream with VLC 2.2.2 and get no audio at all in VLC 3.0.1.
I ran /system/sdcard/autoupdate.sh yesterday.

**Comment by irwando** [comment]
Also having this issue. Video is great, no audio.  Synology Surveillance Center won't even let me set up and audio alert.

**Comment by jmtatsch** [comment]
Maybe you can try out the additional tuning options that pull request #329 offers

**Comment by jmtatsch** [comment]
Should be fixed in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/404. Please reopen if still an issue.
