### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by nik0** [EliasKotlyar/Xiaomi-Dafang-Hacks#24]
Hi,
Thanks for the great job here. 
Is there a way to add a password? I search on internet and apparently BOA doesn't offer this. 
Is it possible to add basic authentification ?

Thanks,
Nik0

**Comment by EliasKotlyar** [comment]
Hello nik0,

I have found a patch for doing this:
https://sourceforge.net/p/boa/patches/18/

I have compiled it, and it seems working. You can use it by uncommenting the line "auth" in the boa.conf.

**Comment by nik0** [comment]
Thanks for being so fast ! I will test that soon ...

**Comment by nik0** [comment]
It's working !
I uncomment the line Auth / Basic:/system/sdcard/config/htpasswd.conf in boa.conf
And I use http://aspirine.org/htpasswd_en.html to generate the htpasswd.conf (using option "crypt()')

Great !!

**Comment by BN-B** [comment]
Hi All,

First of all, great work on this.
Secondly, I'm struggling getting the above method to work. (please treat me as a noob)

I've uncommented the "Auth" line in boa.conf (in Wordpad), but now I cannot access the camera.
When I enter the ip address in chrome, it does not prompt me for a password. It says "192.168.1.x failed to connect".
I have tried root:AO7Ch3nYD/G0s@192.168.1.x, but nothing. I don't think my browser accepts "/" in the address. I have also tried changing the password in htpasswd.conf from root:AO7Ch3nYD/G0s to root:ismart12, but that doesn't work either.
I have also tried changing the port, but that doesn't work.
The camera is working because I can access the stream from tinycam, but the controls in tinycam no longer work.

Could somebody help me out please? (My camera runs on port 80 with the rtsp on port 8554)

Much appreciated!

**Comment by nik0** [comment]
Do you access to the camera with the port number ?
http://192.168.1.x:7000 and then you need to enter the password. This password is not for the camera stream but for the configuration page

**Comment by BN-B** [comment]
Hi nik0, thanks for your message.
Before uncommenting "Auth", I would access the configuration page by simply entering the ip address in my address bar.
After uncommenting I tried with and without the port, but to no avail.

**Comment by nik0** [comment]
Did you check with the port ?
What is exactly the error on the browser?

**Comment by nik0** [comment]
What is your browser? And the URL you entered?
Can you see something in the file /var/log/boa.log ?

**Comment by BN-B** [comment]
Chrome and the url is what I used before uncommenting "Auth" i.e. 192.168.1.31
I also tried using internet explorer
There is no /var/log/boa.log folder

What am I supposed to see when I enter the address?
A prompt for a username/password in a pop-up window?

**Comment by nik0** [comment]
You should use URL like this: http://192.168.1.31:PORT
do you have these lines in boa.conf
`ErrorLog /var/log/boa.log  
AccessLog /var/log/boa.log `

**Comment by BN-B** [comment]
I'm not getting anything
