### ISSUE TITLE
 change the root password

### ISSUE THREAD

**Issue by satanasinc** [EliasKotlyar/Xiaomi-Dafang-Hacks#245]
Hi 

Is there anyway to change the default password?

Thanx in advance for your help and regards

**Comment by Knurlnheim** [comment]
For now, it's not.

But I strongly suggest we figure a way to do it, in order to have a least some level of security.
We already can set users/passwords for lighttp, v4lrtspserver, etc.
I would also like to see a modified dropbear binary that reads an editable "authorized_keys" in order to be able to do password-less ssh.
If we cannot "change" the password, may be we can forbid dropbear to accept password authentication and force the use of private/public keys...

**Comment by sanjeewasam** [comment]
What is the default username and password. I am struggling to figure out

**Comment by jmtatsch** [comment]
root/ismart12

**Comment by sanjeewasam** [comment]
Thanks a lot

**Comment by jmtatsch** [comment]
Close in favour of #141. Please continue the  discussion there.
