### ISSUE TITLE
Android app source?

### ISSUE THREAD

**Issue by sonny-chen** [EliasKotlyar/Xiaomi-Dafang-Hacks#399]
The Android DafangCam app has a couple of problems:

1) Access to config control (status.cgi) fails to work when a self signed SSL certificate is used on the cam side, and
2) fixing the above by disabling the https redirect cam side allows the app's controls to work, but the app mistakenly sends certain commands when initializing the RTSP stream, at least for the Dafang, causing the stream to fail loading (black video).

Is the source code available so we can try to fix these?

Thanks.

**Comment by jmtatsch** [comment]
Do you mean tinyCam?

**Comment by jmtatsch** [comment]
Wasn’t aware that someone is developing a Dafang hack app. Maybe you ask the author if there is an open source repo.

**Comment by amagnolo** [comment]
In my case, using the DafangCam app kills the rtsp service and starts the mjpeg service instead. It took a while to figure it out, I thought that there was something wrong with the camera before finding out that the culprit was the app. Couldn't find the source code either.
I think that recommending the use of that app (apparently broken) is not the best suggestions for newcomers.

**Comment by Dopeyr** [comment]
@mmohamed Any thoughts on the comment above?

**Comment by sonny-chen** [comment]
With the readme recommending the app, and the app's page linking back here, I thought the two projects are developed together -- sorry if I asked at the wrong place.

Meanwhile, my workarounds are disabling https redirect as mentioned above, and commenting out the RTSP service controls in status.cgi.

**Comment by mmohamed** [comment]
Hi,

At first I made this app to control the Cam with the first version of the hack. I planned to share the source code on Gitlab, but after publication on AppStore, my repo contains personal data (password for CI server, keystore for Google protect, ...) and I must clean the repo and its history before sharing it on Github.

As soon as it will be done I will inform you.

For self signed SSL Certificas problem, I will solve it on next release and for the starting of the mjpeg service, it is done on purpose because the HLS does not always work but I will make it optional to the configuration of the cam and dis-synchronize the other calls.

If you want to install the beta release to have the fixes quickly available.

If you encounter problems you can use this issue or directly on medmarouen[at]gmail.com

**Comment by Dopeyr** [comment]
Thanks @mmohamed, great to hear you're working on it :)

**Comment by jmtatsch** [comment]
Closing this as question is answered.
