### ISSUE TITLE
Motion detection: Selecting non-rectangular area

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#424]
At present we can only select rectangle as area of interest, which may not be suitable for everyone. 

We should have option to select non rectangular area, preferably polygon. 

I am not sure how it is implemented, but if polygon selection has limitations, divide the viewport into many smaller rectangles, and user can select the smaller rectangles, just like it is done in tinyCam app.

**Comment by nik0** [comment]
It can be theoretically possible, the new SDK allow 56 areas of detections, I guess you can do what you want.
If someone want to implement a "grid selection" on HTML he is welcomed ...

**Comment by jmtatsch** [comment]
Motion eye has an interesting interface and is open source
https://www.raspberrypi-spy.co.uk/2017/04/detection-area-masking-in-motioneyeos-raspberry-pi/

**Comment by nik0** [comment]
Or something like this: https://www.jqueryscript.net/other/jQuery-Plugin-For-Selecting-Multiple-Areas-of-An-Image-Select-Areas.html

**Comment by aldrenalin** [comment]
In order to have multiple motion detection rectangles (called regions of interest, in the SDK),
according to    imp_ivs_move.h    one provides these regions of interest (roi) in an array called roiRect
and provide the number of such regions, roiRectCnt.
	
How can this be done?
In particular, it seems to me that 
   \firmware_mod\www\cgi-bin\action.cgi 
uses 
  \firmware_mod\bin\setconf
but looking inside setconf it doesn't seem to set roiRectCnt
nor is there a way to specify the set of roi's.
Also, where is the default value, roiRectCnt =1, being set?

So, I'm wondering if I'm missing something here.
(I'm brand new at looking into the dafang-hacks code, so guidance would be appreciated.)


Excerpt from setconf

> 	'm' motion sensitivity (0 to 4) -1 to deactivate motion
  'z' display a circle when motion detected (-1 deactivated, use the OSD color numbers)
 	'r' set detection region (shall be: x0,y0,x1,y1) the server need to be restarted to take into account the new value

**Comment by nik0** [comment]
setconf is a tool that set some value in shared memory that is read by the v4l2server.
when I developed the detection the roi was "only" 4 rects. Now the SDK has changed and it is 52
https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/inc/imp/imp_ivs_move.h

I never tried ...

**Comment by aldrenalin** [comment]
Thanks for your speedy reply. Yes, I've seen from imp_ivs_move.h that 
the maximum number of rectangle (IMP_IVS_MOVE_MAX_ROI_CNT) is	52.

Thanks for clarifying that setconf writes into some chunk of shared memory for the v4l2server.

To me it remains a mystery as to how  to set roiRectCnt 
and to pass the array of rectangles (i.e. regions of interest, roi's).
If we had the source code for setconf and understood the memory map of that setconf writes to, 
that would be a start. 
 setconf sure seems to be restricted to a single rectangle (roi).

**Comment by nik0** [comment]
All the source code is here:
https://github.com/Dafang-Hacks/Main (Setconf and the server)
Setconf need to be modified to handle these 52 rectangles (maybe command line should be not enough and a config file have to be in place)
Then, the difficulty will be to update the web interface for that ....

**Comment by aldrenalin** [comment]
Thanks again nik0 for your replies. 

They have led me to some relevant files including 
sharedmem.h, sharedmem.cpp, setconf.cpp

sharedmem.h  is limited to a single rectangle.

https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/src/ImpEncoder.cpp
has a function ivsMoveStart which initializes 4 rectangles. 

I have essentially zero experience with all of this code, 
and its rather involved, so I'd best leave it to others.

Even commercial products based on the same hardware, e.g. ismartcam spot, wyzecam, 
seem to be restricted to a single rectangle to detect motion.
It's unfortunate, since having multiple (or non-rectangular) motion detection regions seems 
fundamentally important.

**Comment by inode-** [comment]
Not so good with JS+HTML but I will try to implement the multiple area selection on the GUI with that:

https://www.jqueryscript.net/other/jQuery-Plugin-For-Selecting-Multiple-Areas-of-An-Image-Select-Areas.html

The help from someone better than me with JS is appreciated.

**Comment by gysmo38** [comment]
@nik0 I am still working on new UI. I think I can add multiple zone select. Can you modify setconf to allow more than one zone?

**Comment by nik0** [comment]
@gysmo38 
We can add more zones,but does it worth it? Is someone need this feature ?

**Comment by Combie81** [comment]
I'd actually find it useful to block off areas I don't want the camera to capture/watch for movement.

**Comment by saipsa** [comment]
I would also find it useful.

**Comment by gysmo38** [comment]
I think it could be usefull. If you have a room with two windows and want to exclude them. You can do it with more zones.
I am working on the motion page. I can add manages zones but I don't knwon how to modify setconf.

**Comment by nik0** [comment]
OK fair enough
I work on it ...

**Comment by gysmo38** [comment]
Merci, c'est sympa :)

**Comment by nik0** [comment]
OK try last commited binaries
I keep the interfaces unchanged (backward compatibility)
to add 2 regions:
`
setconf -k r -v 1,1,1,1,2,2,2,2
`
1,1,1,1 is coordinate of the 1st region
2,2,2,2 is coordinate of the 1st region
You can have up to 52 regions (I did not test that)
To get the existing defined regions
`
setconf -g r 
`
that will return
```
1,1,1,1
2,2,2,2

```

@gysmo38 
Tu es d'ou ? De l'Isère (38) ou c'est ton age ?

**Comment by gysmo38** [comment]
Thank a lot, I am working on motion page.
I will test it.
@nik0 Les deux c'est mon age et là où je suis :) Je suis à Grenoble.

**Comment by nik0** [comment]
@gysmo38 
J'ai habité y'a très longtemps a Gre. Mon frère y habite toujours d'ailleurs ...

**Comment by gysmo38** [comment]
I finish the page PR #1441
I am not sure it work well. When I test I always saw area 0
setconf -g r output look good. Maybe I missed something.
@nik0 Si tu passes par Grenoble, je pourrais te payer une bière :)
