### ISSUE TITLE
Recording Audio Error

### ISSUE THREAD

**Issue by youqingkui** [EliasKotlyar/Xiaomi-Dafang-Hacks#451]
Xiaomi Dafang Run cmd result:
[root@DAFANG:sdcard]# /system/sdcard/bin/ossrecord /system/sdcard/test.wav
Unexpected EOF on audio device

**Comment by nbourre** [comment]
In my case, when I record video with avconv I don't have audio.

**Comment by nik0** [comment]
ossrecord is no more working.
I need to rewrite a tool for that. Are we sure avconv does not record audio whatever the format ?

**Comment by youqingkui** [comment]
In my rtsp://192.168.31.187:8554/unicast , audio It seems that it has not taken effect yet, and the sound is only intermittent "pong"

**Comment by gz7-design** [comment]
I've just tried avconv, and it doesn't work either. Does some kind of initialization need to be done separately?

[root@DAFANG:fd]# avconv -f oss -i /dev/dsp /tmp/oss.wav
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[oss @ 0x1c91020] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, oss, from '/dev/dsp':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: pcm_s16le
      48000 Hz, 2 channels, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press ctrl-c to stop encoding
Nothing was written into output file 0 (/tmp/oss.wav), because at least one of its streams received no packets.
size=       0kB time=10000000000.00 bitrate=   0.0kbits/s    
video:0kB audio:0kB other streams:0kB global headers:0kB muxing overhead: unknown
