### ISSUE TITLE
Local h264 recording possible Error

### ISSUE THREAD

**Issue by youqingkui** [EliasKotlyar/Xiaomi-Dafang-Hacks#452]
dafang Run cmd 
/system/sdcard/bin/h264Snap > /system/sdcard/video.h264

[root@DAFANG:sdcard]# /system/sdcard/bin/h264Snap > /system/sdcard/video.h264
Segmentation fault

[root@DAFANG:sdcard]# /system/sdcard/bin/h264Snap
failed to AddSensor
IMP_System_Init() failed
Segmentation fault

**Comment by jmtatsch** [comment]
is your h264 server running? Can you view the stream via vlc?

**Comment by Darkblade48** [comment]
I can verify that I am getting the exact same error, using cfw-1.0.bin (Xiaofang 1S)

**Comment by SnOOpeRa** [comment]
Yes me too , exactly the same error , i can not record , rtsp-h264 is running good and can see the stream in vlc , but when try to start the recording stuck with error about the sensor and then show "NOK" in the recording service and do not work... errors are the same s OP , i flashed my xiaofang 1s with cfw-1.0.bin too, so its a some common problem maybe... can somebody help with idea...

**Comment by tookus123** [comment]
These are my observations with Settings -> Recording on the Xiaofang 1S and it probably applies to other devices as well.

1. The recording script /system/sdcard/controlscripts/recording doesn't account for a username and password. If you have a username/password set under Video Settings, the recording won't run. Disable the username and password for testing.

2. Most important is the physical memory limits of the Xiaofang 1S. At the moment there just isn't enough memory to run both rtsp-h264 and avconv which is the recording program at the same time unless i use a video size of 640x360. Anything higher fails or only records for a few seconds before dying.

3. For now i'm running rtsp-h264 at a higher resolution and recording from another computer using avconv. You could also record the stream with vlc or use something like motionyeyeos.

**Comment by gabest11** [comment]
I also ran into these problems and tried to compile ffmpeg (failed) to see if it was any better. But I had no idea it was the shortage of memory. 

ffmpeg also does segmented recording:

ffmpeg -rtsp_transport tcp -y -i "rtsp://root:ismart12@...:8554/unicast" -vcodec copy -c:a aac -strict experimental -map 0 -f segment -strftime 1 -segment_time 60 -segment_atclocktime 1 -segment_format mp4 "capture-%H%M.mp4"

**Comment by tookus123** [comment]
@gabest11 -  I wouldn't say it's a 100% low memory issue but that's what it appears to be based on my experiences and the outputs of top and free commands. The outputs of those commands become unresponsive and jittery until the recording is automatically killed or stopped. Typical symptoms of a low memory issue.

**Comment by nik0** [comment]
@gabest I also had the same problem.
But you can compile avconv
I guess I checked in the compile script

**Comment by Darkblade48** [comment]
@tookus123 So I finally managed to spend some time and made some headway with troubleshooting.

1) Disabled the username/password under video settings. 
2) Set to 640x360, as per your suggestion. 

Now, the "Recording" button can stay on, and I verified this by closing the browser window with the web front end, and then reopening it.

However, the file that is generated on the SD card is only ~200 KB in size, and when opened, is completely empty.

But good news! If I SSH into the Xiaofang, and run this:

`avconv -rtsp_transport tcp -y -i rtsp://192.168.2.115:8554/unicast -vcodec copy -an -t 15 /system/sdcard/DCIM/``date +%Y-%m-%d_%H.%M`.mp4`

Then I can get an MP4 generated on the microSD with no problems!

Now to figure out how to get the recording script to execute properly!

**Comment by tookus123** [comment]
@Darkblade48 - Good on getting recording to work. It might be that audio encoding takes just enough resources to push the memory threshold to the limit and make it avconv crash. I've disabled a couple of services like bftpd and ntpd (running it every 15 minutes as a cron job instead) so i might have a bit more free memory than others. 

Anyways, i think i figured out why Recording doesn't working during startup. I noticed run.sh loops through /system/sdcard/config/autostart and starts those services in order. Since "recording" comes before "rtsp-h264", it get's processed first. That doesn't work because there isn't a video stream to record yet so avconv dies. But before it dies it creates a pid file "/run/recording.pid". That dead service and pid file is why you get the "nok" next to recording. I've modified /system/sdcard/controlscripts/recording so i can click the stop button and get rid of the nok message without rebooting.  Just need to split line 38 into two separate lines and remove the && between them. This is what mine looks like now. You can probably just remove the pid file manually and refresh to get the same effect.

```
    34	stop()
    35	{
    36	  pid="$(cat "$PIDFILE" 2>/dev/null)"
    37	  if [ "$pid" ]; then
    38	    kill "$pid"
    39	    rm "$PIDFILE"
    40	    echo "Stopped recording"
    41	  else
    42	    echo "Could not find a running recording to stop."
    43	  fi
    44	}
```

And this is what the modified run.sh looks like. Commented out autostart and started rtsp-h2664 and recording below in the correct order. I won't leave it like this but it proves rtsp needs to start before recording.

```
## Autostart all enabled services:
#for i in /system/sdcard/config/autostart/*; do
#  $i
#done

/system/sdcard/controlscripts/rtsp-h264
sleep 2;
/system/sdcard/controlscripts/recording
```

I only have those two things enabled in autostart. I suppose we could use something like this to replace the loop. It will cause what ever is listed in the autostart directory to start in reverse order which is what we want as far as recording and rtsp is concerned.

for i in $(ls -r /system/sdcard/config/autostart/*); do 
  echo $i; 
done

**Comment by tookus123** [comment]
Made some more progress. Now i've managed to record 640x360 video with audio. Instead of avconv convert audio to aac, it just copies what's already there (PCM) with the setting i'm using.

In addition to to the changes in my previous post, i've modified /system/sdcard/controlscripts/recording yet again. This time changing 

`-c:a aac -strict experimental`

to

`-c:a copy -strict experimental`

My video settings are 640x360, 10fps, 1000kb/s, SMART.

Audio setting are PCM, 16000, 44100.

**Comment by Darkblade48** [comment]
@tookus123 Alright, so I implemented the changes you mentioned.

Edited the recording script to split up line 38. Also commented out the autostart in run.sh and set it such that rtsp-h264 starts before recording.

However, if I 'stop' and then try to start the recording again, I get NOK. My recording is probably still crashing (need to check video quality settings).

I am using 640x360 like you, but 20 fps, 2000 kb/s bitrate for video.
My audio settings are the same as yours, except set to MP3 instead of PCM.

Just to confirm, to change the video settings, you are editing the rtspserver.conf file inside the /config folder? I tried changing them on the web front end, but the changes never seem to 'stick'. In fact, if I change the resolution, it reverts back to 1600x900 if I scroll around/refresh the web front end.

Right now, I have edited the rtspserver.conf file to hard code in these changes.

**Comment by Darkblade48** [comment]
@tookus123 

Sorry for the wall of text. I left my previous comment up just for posterity, but I fooled around a bit more and have good news/updates for you.

Edited recording script to split up line 38. Commented out sections in run.sh as above, and pasted in code to start rtsp-264 prior to recording. 

Recording starts up automatically now. Stopping and then starting again = OK. PID generated. No problems!


Changed rtspserver.conf file video and audio settings:
640x360 resolution, 10 fps, 1000 kb/s bitrate.
Audio set to 16000, 44100, PCM

recording script (line 29) reads

`    /system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://192.168.2.115:8554/unicast -vcodec copy -c:a copy -strict experimental "$RECORDING_PATH"  &>/dev/null &`

**Comment by tookus123** [comment]
@Darkblade48 

Oops.. forgot to remove "echo"  from the loop. I'll edit so nobody else has to figure it out. I haven't had time to play with it yet. Do you have anything else in the autostart directory other than rtsp-h264 and recording? You could try to add "sleep 2" to the loop. That'll give rtsp- h264 2 seconds to start before recording is started (just like the hardcoded version). You can play around with that value. Might need more or less. It'll make bootup a little slower since it'll wait 2 seconds between each autostart service you have configured. There might be better ways but hopefully one of these will work until autostart is worked on.

```
for i in $(ls -r /system/sdcard/config/autostart/*); do
  $i;
  sleep 2;
done
```

Or something like this might be better because it'll only wait 2 second after rtsp but not other services. Neither of these are tested but you can give them a shot if you're up to it.

```
for i in $(ls -r /system/sdcard/config/autostart/*); do
  $i;
  if [ $i = /system/sdcard/config/autostart/rtsp-h264 ]; then 
    sleep 2;
  fi;
done
```
I haven't looked into the video file storage. But yeah, it's going to record until the sdcard or usb storage is full. Definitely needs some work.

**Comment by Darkblade48** [comment]
@tookus123 

I only had rtsp-h264 and recording in the autostart directory. 

I ended up using your modified code (to ls -r the autostart directory, so that rtsp-h264 starts up before recording), with the 2 second delay and it works well!

Now there is no need for hard coding, and the those two services seem to be good.

I'm going to start to play around with video file storage and video segmentation. At the current video/audio settings (mentioned above), it's about 10 MB per minute of feed, so a 32 GB microSD lasts roughly (32000 MB / 10 MB = 3200 minutes == 53 hours, just over 2 days). 

I'm hoping to get video segmentation working (say new files every hour or something), then as the microSD gets filled, it deletes the oldest hour. Obviously for long term monitoring, it'd be best to reduce file size and/or offload the files to something else (USB, NAS, etc), but that's for later.

**Comment by chaseadam** [comment]
This thread is great for a local recording option while leaving the rtspserver running (with motion detection).

I did want to chime in on the original symptom of h264Snap (segmentation fault), I was able to use that tool as soon as I stopped my rtsp server. Is it possible h264Snap cannot run at the same time as v4l2rtspserver-master?

**Comment by Darkblade48** [comment]
@chaseadam How are you triggering the h264Snap? I took a quick look, but did not seem to see it on the web front end. 

I can give it a shot to see if I can take a snap using h264Snap while the RTSP server is running.

**Comment by ferrolho** [comment]
FYI, I am able to get a video+audio stream on VLC with the following settings:

![img](https://i.imgur.com/5WyJji5.png)
![img](https://i.imgur.com/R1Krtch.png)

More, I can record a video+audio clip and save it locally with:
```bash
avconv -rtsp_transport tcp -y -i rtsp://your.camera.ip.address:8554/unicast -vcodec copy -c:a copy -t 5 /system/sdcard/DCIM/`date +%Y-%m-%d_%H-%M-%S`.mp4
```

However, there is a considerable delay on the audio channel. Any insights regarding this?

**Comment by DoeEensGek** [comment]
So are there any updates on this?

I want to use my cam just for recording continously or for 10hours a night, on  a local 32 gb sdcard.
Recording the rtsp transport limits to a low video size. Advised is to just only recording or stream, so how to record only?

**Comment by Hussamfhaily** [comment]
why does homebridge crash when I press record video button?

**Comment by kaidoristm** [comment]
Audio format: PCMU
File format should be .mov (mp4 doesn't support PCMU)
Any resolution works!
Tested with different bitrate's anything above 5000 can cause problems with stuttering audio and artifacts.
- ar 44100 = Set the audio sampling frequency

`/system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://USERNAME:PASSWORD@YOUR_CAMERA_IP:8554/unicast -vcodec copy -c:a aac -ar 44100 -strict experimental -t 30 /system/sdcard/DCIM/Videos/`date +%Y-%m-%d_%H.%M`.mov`
