### ISSUE TITLE
Audio always 8000 Bit

### ISSUE THREAD

**Issue by goermezer** [EliasKotlyar/Xiaomi-Dafang-Hacks#469]
Audio settings doesn`t change when I set it in the web ui. It doesn`t matter, what I select. The quality is always very bad. Sounds like 8KBit. The older versions were set to 64KBit MP3 and that sounded not too bad. Even OPUS sounds like 8KBit.

I restarted the rtsp server. But no change. Interestingly VLC shows the right codec and bitrate.

**Comment by nik0** [comment]
The mic is only 8k so 64kbit was only upscaling.
Did you play with the volume ? and filters?
Did you compare with the original F/W ?

**Comment by goermezer** [comment]
I can not imagine, that the mic is 8k. I think even the cheapest condenser mic is more capable.
I played with volume, filter and codec. Some codec has lesser scrambling and some more. But the voice always sound like 8K.

I have two examples here. The good one was saved from the h264/mp3 stream as aac with ffmpeg in the past. I exported it with VLC to mp3. The bad one is from today. Same source mp3 stream, but no AAC inbetween. The old one is much cleaner and better than 8k.
[voice-quality.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2106341/voice-quality.zip)

**Comment by goermezer** [comment]
Its a dafang

**Comment by tssva** [comment]
I noticed that aec isn't being enabled and it is in the original firmware. Even if we don't currently have  two way audio enabling aec may improve the sound since it also enables automatic gain control. Enabling it does require having webrtc_profile.ini in the /etc directory. I am getting ready to submit a PR which among other things add this to the list of files copied over to the /system/sdcard/etc directory.

Another issue I experience is a significant delay between the video and audio which isn't present in the original firmware. I noticed that the sound frames are being fetched from the ALSA device and then encoded. The imp sdk supports attaching an encoder to the imp processing. Basically you register a call back function which the imp calls whenever it has a frame to be encoded. If it hasn't already it might be worth trying to see if it improves the sync between video and audio.

**Comment by nik0** [comment]
@goermezer 
My bad, with the new sdk it seems that the bitrate can be increased (for now I am stuck to 24000) i am trying to figure out why 44100 is not working ...

**Comment by goermezer** [comment]
@nik0 
Thanks, even 24K would be an improvement.

**Comment by nik0** [comment]
@tssva good catch ! 
Indeed it is working but I have to deactivate some filters calls when bitrate is higher than 16k

**Comment by nik0** [comment]
@tssva where are you from your PR ?

**Comment by tssva** [comment]
PR #485 which included copying webrtc_profile.ini to /system/sdcard/etc has already been committed.

**Comment by nik0** [comment]
Please see https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/523

**Comment by jmtatsch** [comment]
Should be fixed. If not please reopen.
