### ISSUE TITLE
No SSH after upgrade

### ISSUE THREAD

**Issue by jresende7** [EliasKotlyar/Xiaomi-Dafang-Hacks#558]
Hello, i upgraded recently to the new version of the firmware and now i can't log my cam by ssh.

I tried "root", "ismart12" as a password but no success !!

Thanks for the help

**Comment by tookus123** [comment]
Probably this.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/546#issuecomment-403164276

**Comment by jresende7** [comment]
can anyone help me ? I formated my sdcar and copied the content on "firmware_mod" folder to the sdcard...i cant ssh to it !!!!

**Comment by jmtatsch** [comment]
Is your wpasupplican.conf valid? What does your startup.log say?

**Comment by jresende7** [comment]
Yes, and I have connection. If I put the up on a browser I can authenticate with “root” “ismart12”

But not on ssh...it’s very awkward !! And I sincerely don’t know what to do !!

**Comment by tookus123** [comment]
I'm not sure. If i were you i would wipe the sdcard, reformat it, download the zipfile archive, and copy the contents of firmware_mod to the sdcard. If that didn't work i would try the same steps but grab the files with git instead of the zip archive.

Also have a look at this thread closed thread. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/518

**Comment by jmtatsch** [comment]
What camera is this?

**Comment by jresende7** [comment]
It's a Xiaomi dafang.

**Comment by jresende7** [comment]
@tookus123 thank you. I can log into ssh. I've done what @manianac did 

"I reverted to an earlier commit, that booted fine, than auto-updated."

But now, strangely i don´t have a ssl certificate when i log into web page .

**Comment by jmtatsch** [comment]
Please wipe your sd and start from scratch.
