### ISSUE TITLE
Kind of OT - CHUANGMI 720p - any hint/help?

### ISSUE THREAD

**Issue by Unclezz** [EliasKotlyar/Xiaomi-Dafang-Hacks#618]
Dears,
it seems this project is the most active in the development of the xiaomi cameras alterantive fw.
I successfully installed the Dafang-hack on mine and I am really thankfull for all your efforts.
I now have a CHUANGMI 720P camera that is using a GM1835S chipset.
I would like to try if it is possible to have also on this very cheap model an alternative fw.

Is there anyone who is willing to help with initial steps on how to achieve that?

I alrady dismounted camera and seen possible TX-RX pin to use to access via console. I am going to order today a USB adapter. Can you guide me to next steps?
Here is inside:
![photo_2018-08-04_08-54-51](https://user-images.githubusercontent.com/42074421/43677158-b4e3cf9a-97fd-11e8-8765-8e581a7bdf31.jpg)
![photo_2018-08-04_08-55-04](https://user-images.githubusercontent.com/42074421/43677159-b501aa4c-97fd-11e8-9496-777ab059ed5a.jpg)

Any help will be highly appreciated! 

P.S.: I also asked help on https://github.com/Filipowicz251/mijia-1080P-hacks as it is apparently running similar chipset.

**Comment by EliasKotlyar** [comment]
Hello @Unclezz,

I will try to explain some steps which i have taken:
1. Get serial access
2. Dump the all filesystems from the device
3. Try to get a telnet/ftp connection. 
4. Document all things for later use
3. Find a way to provide access to the camera without opening/soldering
4. Add new features/Start software development

Feel free to ask any question about this "general" topic anytime. 

Greatings
Elias

**Comment by gabest11** [comment]
@EliasKotlyar 

Sorry to hijack, I have this camera, and also the new mijia 1080p, which has the same internals as the dafang. Do you think xiaomi could program uboot to not accept any input on serial to break before loading the kernel? There is no command prompt at the end either. I can still read the log and see the echo of my keystrokes. Currently waiting for the flash programmer and soic/sop8 clip to arrive, with that it will not be hard to repack the filesystem with some kind of remote access, telnet at least.

There is another thing. In RD_T20_BULL_V10_20160912B.pdf, under BOOT CONFIGURATION / LED, the two LED connections also control where to boot from. With a hardware mod I think it could be told to use the SD card. But I am not sure how it would interfere with the LEDs.

**Comment by EliasKotlyar** [comment]
@gabest11 : 
Can you write anything when the kernel is booted? If not: check the connection - maybe you have connected the wrong pins. Also check the voltage. It seems rather an hardware issue. 

I would not recommand to try to change the boot configuration using hardware. It may involve a little bit more than just desoldering some LEDs. 

Can you also please tell me what kind of device you have?
There are several Mijas:
https://www.gearbest.com/ip-cameras/pp_009981882806.html?wid=1433363
https://www.gearbest.com/ip-cameras/pp_009991451325.html?wid=1433363

**Comment by gabest11** [comment]
This one: https://www.gearbest.com/ip-cameras/pp_009981882806.html?wid=1433363

White back, not removable from the stand. It has the T20 chip. The old version with the black and removable camera had GrainMedia, almost identical to the one on the pictures above, only half the memory. 

If I don't connect the third, I don't even get the keystroke echo, only the log comes through. This is the (bootlog)[https://github.com/gabest11/Xiaomi-Mijia-1080p-2018/blob/master/bootlog.md]. Note, there is no "press any key" message.

Once I get the flash programmer, I will look for entry points in the firmware, for this one and also for the 720p camera. The old mijia 1080p was hackable because they allowed it to boot from the sd card with the right files and the private key to sign it was on the device. 

The LED connections allow it to boot from the sd card on 0/0, in theory, just copying the whole firmware to the card and cutting the connection should do it, but I am not going to destroy it yet :)

**Comment by EliasKotlyar** [comment]
@gabest11 : I think we should continue our talk in a dedicated issue:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/624

**Comment by Unclezz** [comment]
So, I tried to solder 0-RX, 0-TX and GND with wires and then I had them connected to usb/uart adapter. But there is no output. Same using 2-RX and 2-TX. 
Is it possible that the ports are not serial?
