### ISSUE TITLE
Read-only file system and schedule recording

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#62]
Hello,
I found a few issues..

1st I would like to add alias to profile. I got messeage that etc is read-only.
How can i change it?

2nd
I would like to schedule recording to my sdcard for example:
--loop recording with max size per file 200mb
--retention policy 7days

Is it possible?

3rd Can I see the video via chrome or another browser ?

4th Another problem founded:
```
[root@DAFANGHACKS:~]# /system/sdcard/bin/h264Snap
failed to AddSensor
IMP_System_Init() failed
Segmentation fault
[root@DAFANGHACKS:~]#
[root@DAFANGHACKS:~]# /system/sdcard/bin/h264Snap > /system/sdcard/video.h264
Segmentation fault
[root@DAFANGHACKS:~]#
```

5th the last thing is... timestamp overlay missing could I enable it?

**Comment by EliasKotlyar** [comment]
Hello @wojtulab ,

1. Thats not easy possible. The /etc/ Folder is locked because of the original firmware. You will have to modifiy the firmware to "unlock" it:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md
2. You can achieve this trough Crontabs and the h264snap solution
3. Yeah, you can using the the HLS-Feature:
https://github.com/mpromonet/v4l2rtspserver
4. You cannot run h264snap and v4l2-server on the same time. Disable one of them.
5. The Timestamp Overlay was already implemented to the v4l2-server. Just update to the last Version


Greatings
Elias

**Comment by wojtulab** [comment]
thank you! One more question...

is it possible to create a password for rtsp and http connection? It could be basic auth. Anything?

**Comment by EliasKotlyar** [comment]
Hello @wojtulab ,

You can protect the HTTP-Connection trough:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/24

The RTSP can also be protected using the commandline-parameters:
https://github.com/mpromonet/v4l2rtspserver

Greatings
Elias

**Comment by wojtulab** [comment]
ok thank you agan, closing.

**Comment by wojtulab** [comment]
sorry, but where is exactly crontabs? I can't find it, edit and run as service...

**Comment by EliasKotlyar** [comment]
Hello @wojtulab ,

Run /system/sdcard/bin/busybox. Its a custom busybox binary, which has crontabs inside. The original one is not working good.

**Comment by wojtulab** [comment]
ok i see, its working but is it possible to run this cron like a normal cron - service?
I am not sure if it fire recording for example at 14:16 and stop it at 14:39.

**Comment by EliasKotlyar** [comment]
You can make something like:

14 16 0 0 0 /h264-snap > file.h264
14 39 0 0 0 killall h264-snap

**Comment by wojtulab** [comment]
great, thank you very much!

**Comment by wojtulab** [comment]
/system/sdcard/bin/busybox crontab -e
crontab: can't change directory to '/var/spool/cron/crontabs': No such file or directory

is it normal?
