### ISSUE TITLE
ZoneMinder - Controls not working

### ISSUE THREAD

**Issue by Unclezz** [EliasKotlyar/Xiaomi-Dafang-Hacks#634]
Hi,
I configured ZoneMinder as per guide on main page and everything works ok except the control of the camera.
I noticed in the logs of ZM that when I click the arrows there is following error:

`ERR | Error check failed:'500 Can't connect to XX.XX.XX.XX:443 (certificate verify failed)' | zmcontrol.pl`

Can this be the problem? If so, how this can be fixed?

**Comment by Unclezz** [comment]
I did a slight change to the file Xiaomi.pm fter installing on my Debian 9.0 the packages  libnet-ssleay-perl and libcrypt-ssleay-perl and adding at the very beginning:

`use IO::Socket::SSL;`

Then I arranged a change on sub "open" (in **bold**) to remove the checks on SSL:

`
sub open
{
    my $self = shift;

    $self->loadMonitor();

    use LWP::UserAgent;
    **$self->{ua} = LWP::UserAgent->new(
        ssl_opts => {
                #verify_hostname => 0,
                SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE,
         });**
    $self->{ua}->agent( "ZoneMinder Control Agent/".ZoneMinder::Base::ZM_VERSION );

    $self->{state} = 'open';
}
`
Now the LOG message is changed and is reporting that I am not authorized:

ERR | Error check failed:'401 Unauthorized' | zmcontrol.pl |  

It's like not passing credentials or sending them wrongly. I double checked them and they are ok in ZM configuration.... AAAAARGH!!

**Comment by bchristian68** [comment]
@Unclezz 

Thanks for your input, I was having the same problem controlling mine too.  As it turns out, I was able to use your suggestion with a small modification to get the PTZ functioning in Zoneminder with the Dafang.  Since the Dafang PTZ requires https request on port 443 to work, I also modified the Xiaomi.pm in the sub sendCmd section as follows:

`    my $req = HTTP::Request->new( GET=>$self->{Monitor}->{ControlAddress}."/cgi-bin/action.cgi?cmd=$cmd" );` 

This allows you to configure the control tab like this (adding https://):

![image](https://user-images.githubusercontent.com/9382752/46231880-1ce02480-c333-11e8-8fe6-de250b8695f4.png)

Also, I un-commented the verify_hostname => 0, line in your code.

That's it.  I can control the cams now, however I'm still getting errors in the log like these:

Socket /var/run/zm/zms-519496s.sock does not exist. This file is created by zms, and since it does not exist, either zms did not run, or zms exited early. Please check your zms logs and ensure that CGI is enabled in apache and check that the PATH_ZMS is set correctly. Make sure that ZM is actually recording. If you are trying to view a live stream and the capture process (zmc) is not running then zms will exit. Please go to http://zoneminder.readthedocs.io/en/latest/faq.html#why-can-t-i-see-streamed-images-when-i-can-see-stills-in-the-zone-window-etc for more information.

I'm not sure if that is caused by the mods, but I never got that prior to this.

**Comment by alexdelifer** [comment]
For those following allow at home.

```
package ZoneMinder::Control::Xiaomi;

use 5.006;
use strict;
use warnings;
use IO::Socket::SSL;

require ZoneMinder::Base;
require ZoneMinder::Control;

our @ISA = qw(ZoneMinder::Control);

our %CamParams = ();

# ==========================================================================
#
# Xiaomi Dafang Control Protocol
#
# On ControlAddress use the format :
#   USERNAME:PASSWORD@ADDRESS
#   eg : https://root:ismart@10.0.100.1
#
# ==========================================================================

use ZoneMinder::Logger qw(:all);
use ZoneMinder::Config qw(:all);

use Time::HiRes qw( usleep );

sub new
{

    my $class = shift;
    my $id = shift;
    my $self = ZoneMinder::Control->new( $id );
    my $logindetails = "";
    bless( $self, $class );
    srand( time() );
    return $self;
}

our $AUTOLOAD;

sub AUTOLOAD
{
    my $self = shift;
    my $class = ref( ) || croak( "$self not object" );
    my $name = $AUTOLOAD;
    $name =~ s/.*://;
    if ( exists($self->{$name}) )
    {
        return( $self->{$name} );
    }
        Fatal( "Can't access $name member of object of class $class" );
    }

sub open
{
    my $self = shift;

    $self->loadMonitor();

    use LWP::UserAgent;
    $self->{ua} = LWP::UserAgent->new(
        ssl_opts => {
                verify_hostname => 0,
                SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE,
         });
    $self->{ua}->agent( "ZoneMinder Control Agent/".ZoneMinder::Base::ZM_VERSION );

    $self->{state} = 'open';
}

sub close
{
    my $self = shift;
    $self->{state} = 'closed';
}

sub printMsg
{
    my $self = shift;
    my $msg = shift;
    my $msg_len = length($msg);

    Debug( $msg."[".$msg_len."]" );
}

sub sendCmd
{
    my $self = shift;
    my $cmd = shift;
    my $result = undef;
    printMsg( $cmd, "Tx" );

    my $req = HTTP::Request->new( GET=>$self->{Monitor}->{ControlAddress}."/cgi-bin/action.cgi?cmd=$cmd" );
    my $res = $self->{ua}->request($req);

    if ( $res->is_success )
    {
        $result = !undef;
    }
    else
    {
        Error( "Error check failed:'".$res->status_line()."'" );
    }

    return( $result );
}




# Reset the Camera
sub reset
{
    my $self = shift;
    Debug( "Camera Reset" );
    $self->sendCmd( "reboot" );
}

#Up Arrow
sub moveRelUp
{
    my $self = shift;
    Debug( "Move Up" );
    my $cmd = "decoder_control.cgi?command=0";
    $self->sendCmd( "motor_up" );
}

#Down Arrow
sub moveRelDown
{
    my $self = shift;
    Debug( "Move Down" );
    my $cmd = "decoder_control.cgi?command=2";
    $self->sendCmd( "motor_down" );
}

#Left Arrow
sub moveRelLeft
{
    my $self = shift;
    Debug( "Move Left" );
    my $cmd = "decoder_control.cgi?command=4";
    $self->sendCmd( "motor_left" );
}

#Right Arrow
sub moveRelRight
{
    my $self = shift;
    Debug( "Move Right" );
    my $cmd = "decoder_control.cgi?command=6";
    $self->sendCmd( "motor_right" );
}

#Home Button
sub presetHome
{
    #Unimplemented - workaround for ZM memory issue
    Debug( "Move Home" );
}

1;

```
