### ISSUE TITLE
Firmware / Setup problem... 

### ISSUE THREAD

**Issue by Pomurphy** [EliasKotlyar/Xiaomi-Dafang-Hacks#64]
Hi

Using the Dafang cam for a week with Xiaomi App.. but was not really helpful to always use the phone to access it.. so wanted to use antoher way.. So, followed the guideline, checked everywhere.. can't find the problem just on the first start of the procedure... 

Procedure : download cwf..bin > rename to demo.bin > copy to a fresh FAT formatted micro SD
Hold Setup and plug USB cable.

After using several micro SD cards including a Samsung, from 1 to 8 GB..  the effect is always the same. It clacks once, put an orange light, after 12 seconds, clacks twice in a row, and starts speaking Chinese while rotating this in a boot loop. 

Would you have any clue ?
Thanks in advance,
Pierrick

**Comment by kszere** [comment]
#
# General informations

The custom firmware (CFW) bootloader will boot from MicroSD only if a MicroSD is plugged in and has a "run.sh" file on it. Otherwise it will load the stock firmware from the flash memory.

## Installation of the custom firmware with the MicroSD bootloader

1. Download [CFW-Binary](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/cfw/cfw-1.2.bin) file.
2. Format your MicroSD to FAT (ex. FAT16 or FAT32). NTFS, EXFAT etc. won't work.
3. Put file to MicroSD and rename it to "demo.bin". **There should be no other files on the MicroSD!** This is really important and it won't work if there are any other files on there.
```
MicroSD:/
└── demo.bin
```

4. When poweroff the Dafang camera, remove the power cable and plug the MicroSD into the Dafang.
5. Hold the setup button on the Dafang camera.
6. Plug in the USB power cable.
7. Wait until the firmware has finished flashing (like 5 minutes). Disconnect the power as soon as the camera starts moving.
8. Remove the MicroSD and try to start the Dafang camera.
9. You should see the blue led shining up for 5 seconds (not blinking) **before** the base starts moving. If not, something went wrong. You should try another MicroSD. Start over from step 1.


## Installation of the new Firmware on MicroSD

1. Clone the [EliasKotlyar/Xiaomi-Dafang-Hacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks) repository from GitHub. If you use Microsoft Windows, download the repository as *.zip file.
2. Copy everything from "**firmware_mod**" folder into the **root** of the MicroSD.
It should look like this:
```
MicroSD:/
├── bin
├── config
├── run.sh
├── scripts
├── www
└── run.sh
```
3. Modify the file `/config/wpa_supplicant.conf` on the MicroSD to match your WiFi settings.
4. Insert the MicroSD and start the camera.

## Updating Firmware on MicroSD

If you already have a current custom firmware with custom bootloader installed, you only need to update the content of the MicroSD.

1. Backup your contents MicroSD.
2. Remove all files from the MicroSD.
3. Put everything from "**firmware_mod**" folder into the **root** of the MicroSD.
4. Copy the backed up `/config/wpa_supplicant.conf` and other files (if you need) from step 1 back into the config folder.

**Comment by Edmond76** [comment]
Bonjour,
J’ai reçu ma cam en version FW 5.5.1.197.
J’ai tenté l’installation du CFW mais celui-ci est pour la version .200
J'ai exactement les mêmes symptômes que @Pomurphy : un clac, lumière orange puis 2 clacs et la base tourne...
L’application me propose que le FW 5.5.1.243 donc pas de passage par le .200. 
Dois-je installer « manuellement » le firmware officiel en .200 pour pouvoir passer le CFW 1.2 ?

Hi,
I received my Dafand one month ago and I've got the same issue as @Pomurphy 
Even if I follow severales times the process as written, it doesn't work.
It seems that the hack works with FW 5.5.1.200. Do we need to update manually to FW .200 and then try to install the hack again? If yes how to install official firmware without Mi Home app? ( who only propose me the last FW 5.5.1.243)

Edmond

**Comment by muertrero** [comment]
hi
may i ask,how to install the original firmware..after updating to the latest firmware my dafang doesnt work anymore the yellow light is just steady

**Comment by MasterPIC** [comment]
@muertrero May I ask you to read documentation and, in any case, provide more details when reporting an issue?

**Comment by messerchmidt69** [comment]
hello, followed same:

Clone the EliasKotlyar/Xiaomi-Dafang-Hacks repository from GitHub. If you use Microsoft Windows, download the repository as *.zip file.
Copy everything from "firmware_mod" folder into the root of the MicroSD.
It should look like this:
MicroSD:/
├── bin
├── config
├── run.sh
├── scripts
├── www
└── run.sh
Modify the file /config/wpa_supplicant.conf on the MicroSD to match your WiFi settings.
Insert the MicroSD and start the camera.

--- any no dice. using a 32gb kingston card formatted to fat32. edited the /config/wpa_supplicant.conf with my details. still no luck. suggestions? maybe change xiaomi firmware  to another version first? works with their app. cant get the third party to flash.

**Comment by Pomurphy** [comment]
Thanks for feeding back. 

@kszere I am still not able to free my dafang from Xiaomi firmware.. i got some experience in tomorrow tweaking.. though here, missing information.. just like Edmond and Messerschmidt..

Any idea where I could get logs?

Thanks

**Comment by kszere** [comment]
Please try open camera and connect UART (ecample with cp2102pl chip) and connect to Putty or minicom on Linux. Please analyze return information.

**Comment by nbourre** [comment]
I received my cam today. I tried to install the CFW, but it does not seem to work. I held the setup button until I heard the lady voice and unplugged the camera.

- How long should we hold the setup button before releasing it?
- What is the difference between "Installation of the custom firmware with the MicroSD bootloader" and "Installation of the new Firmware on MicroSD" are these two different methods or a sequence of action we have to do?

It is not clear.

**Comment by cb416** [comment]
Agreed.  When to release the button, and what the camera might be doing is completely missing from the instructions.   Does the camera do nothing when it's flashing?  Because when it fails there is a lot of activity.  Release the setup button pretty quickly and you get a yellow light for like 10 seconds, 1 click, flashes blue, chinese voice, base motor spins, endless flashing yellow light. Hold the button until the solid yellow turns off, and you get two clicks and then the base spins with an endless yellow flashing light.   I've tried this dozens of times now, I tried it with FAT32 and eventually partitioned to 4GB so I could use plain old FAT.  Each attempt, moving the microSD card to my PC to remove the time_lapse directory and log files the camera writes. 

Looking at the OpenIPC, the directions there suggest holding setup for 10 seconds before plugging in power and holding for a further 10 seconds.

**Comment by cb416** [comment]
Saw in another comment that the flashing can take 10 seconds, which seems strange with the official instructions asking to wait 5 minutes.  I took the chance and moved onto the second step of installing the firmware_mod directory, but no luck.  No solid blue light.  Camera behaves the same, whether the microsd is in or not.   Solid yellow for about 10 seconds, 2 clicks, base moves, yellow light flashes endlessly.

**Comment by Edmond76** [comment]
Ok I've find the solution! I hope it will help you:

From this page [Hack](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/hacks/cfw), instead of right clic and save on "cfw-1.2.bin" ( in that case you will download a html file named cfw-1.2.bin of 46Ko.....) you have to clic on it and then, on bottom right ( at the left of button "History"), click on "Download" button.

You'll now download a 10.6Mb file...rename it demo.bin...you know how to do after ;)

Good luck !

==================

Bon j'ai bien ri. Concernant mon soucis à l'étape 1 sur l'installation du hack j'ai finalement réussi.

J'avais fait clic droit et télécharger sur "cfw-1.2.bin" ce qui me donnait en fait un fichier de 46Ko qui n'était rien d'autre qu'une page html...forcément même renommé en demo.bin ça ne restait que du code html lol...

Bref solution : il faut appuyez sur "cfw-1.2.bin" à partir de ce lien [Hacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/hacks/cfw) et ensuite en bas à droite, en face de "10.6 MB" ( et donc pas 46ko ^^ ) et à gauche de "History,  il y a un bouton "download" sur lequel on appuie et ô magie c'est le bon fichier à renommer en demo.bin ^^

Bon n'étant pas trop habitué au site github ne me jeter pas la pierre svp ;)

**Comment by Pomurphy** [comment]
Ah oui.  Bonne remarque car je me demandais comment un fichier de 10 ko
mettait 10 minutes à s'installer.
J'essaye plus tard.

Good hint. I was really thinking and doubting on how a 20kb file could take
10 minutes to install.
Will try later.

Merci, thanks

**Comment by EliasKotlyar** [comment]
Hello everyone,

I have released a new Microsd-Bootloader, which can be found under the normal Download-Link. Its just an update of the original Firmware to 5.5.243. If you are on 5.5.200 - just update trough the MI-App. The Bootloader wont be removed.

**Comment by EliasKotlyar** [comment]
Hello everyone,

I have released a new Microsd-Bootloader, which can be found under the normal Download-Link. Its just an update of the original Firmware to 5.5.243. If you are on 5.5.200 - just update trough the MI-App. The Bootloader wont be removed.

**Comment by cb416** [comment]
Thank you, Edmond76.  I should have guessed that 36kb file was the wrong size!  I took bootloader too literally I guess.  I didn't think it was the actual firmware we were updating!  I'm trying 1.3 now.

**Comment by kevincaradant** [comment]
Hi

Maybe it's a dumb question, but have I to let the SD card with the custom firmware in the camera or after to start it with the SD card, I can remove it? I don't want to do a mistake... Thank you :)

**Comment by hubmon** [comment]
Card must be in camera to run this hack.
If the card is removed, Xiaomi firmware will run.

**Comment by juanmol** [comment]
similar problem here.
Format the SD and copy the cfw-1.3.bin (10.8MB) to it. Rename to demo.bin.
Insert the SD, hold the button and power the camera.
Wait until led turns blue, then unhold the button.
The camera moves and have ping (i dont understand this), wait 5 minuts and unplug.
Delete all files on the SD, the demo.bin and two more directories.
Copy the content of firmware_mod.
Modify the wpa_supplicant.
Put the sd into the dafang and power it.
Wait ... wait .... wait ... the led is always yellow, no new devices on my DHCP, there is no ping to the previous IP.
I have try with 3 sd cads.

Please, what i'm doing wrong? Need help. Regards.

**Comment by stayingarmed** [comment]
I'm having the same problem as juanmol. I've done everything and after putting the card with the files and folders in, it turns on orange, goes blue for about 2 secs, and goes orange and never does anything else. I have used an ip scanner and it isn't found on my network at all.

**Comment by Edmond76** [comment]
@stayingarmed @juanmol 
Are you sure you have follow my comments bellow?

> From this page Hack, instead of right clic and save on "cfw-1.2.bin" ( in that case you will download a html file named cfw-1.2.bin of 46Ko.....) you have to clic on it and then, on bottom right ( at the left of button "History"), click on "Download" button. You'll now download a 10.6Mb file...rename it demo.bin...you know how to do after ;)

It may not resolve your issue but you can check this anyway!

**Comment by juanmol** [comment]
Ok, i have fixed it!!. I have repeat the full process (again) but in Linux, with git clone (i don't think this had fixed the problem) and renamed the wpa_supplicant.dist to wpa_supplicant.conf
Now it's working!!

**Comment by messerchmidt69** [comment]
going to try that

have not been able to get it going

**Comment by luisbarreto** [comment]
Hi everyone,
I'm also having trouble loading custom firmware to Dafang camera. Tried several times with a clean FAT micro SD with only demo.bin (~10 MB) and I can't get the blue led.
I don't know if I keep the setup button pressed enough time since when the camera starts, the micro usb power cable kick of my fingers...
For the record I am also running linux to prepare the SD, download, check the hash and guarantee that demo.bin iis the only file in the card.
@juanmol can you please share anything that I can use to program the bootloader to the camera?
Thanks for any help.

**Comment by jmtatsch** [comment]
The readme should now be much more concise. Lets close this.

**Comment by belch85** [comment]
I'm having the same problem - more details [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/545).

I've tried 3x microSD cards, I'm using the correct 11MB demo.bin file, correct file system - the camera will not initiate bootloader (no blue light, after holding the setup button for about 13 seconds the base spins and kicks me off).  Same thing happens when I try to downgrade the firmware [here](https://github.com/samtap/fang-hacks/wiki/HowTo:-Flash-original-Xiaomi-firmware-from-sdcard-(factory-reset)).

Currently the camera is not paired with Mi Home app, so I'm about to try @luisbarreto method by connecting it first and trying again, though I've already done this numerous times.

**Comment by gabest11** [comment]
I could never pair my camera with Mi Home, tried all day after receiving it, then I gave up and flashed demo.bin no problem.

**Comment by T3rm1** [comment]
I think I have the same problem. The camera doesn't load apply the custom firmware. The is no blue light. The camera just boots normally and after about 13 seconds it starts moving the base. Also, pairing with Mi Home is not possible any more outside China.

**Comment by DanielePetrarolo** [comment]
Same problem here. No way to hack this camera anymore?

**Comment by T3rm1** [comment]
I was able to solve the problem. I created a 512MB partition on the sd card and then it worked.

**Comment by edster69** [comment]
Finally got this to work after hours of fiddling about. TL;DR DO NOT use a SDHC or SDXC to install the firmware, so you'll need to use a card up to and including 4GB in size. I formatted with FAT, but FAT32 may work too.

**Comment by ac13332** [comment]
Tried countless times and got nowhere.

- 64GB Class 10 SD ,working on a 512mb primary partition (FAT and FAT32 tried). 

- Otherwise the SD card is completely blank

- Paired camera with app before hand - also tried without it being paired.

- Definitely the correct 10mb .bin file.

Main issue is that when I insert the SD and turn it on (holding Setup button). The blue light comes on and only lasts 5-10 seconds, It then spins, speaks Chinese, and flashes orange or one time went solid blue - either way nothing happened.

No idea where to go next!
