### ISSUE TITLE
Xiaomi Xiaofang 1S - Network not working?

### ISSUE THREAD

**Issue by stenkarlsen** [EliasKotlyar/Xiaomi-Dafang-Hacks#662]
I've got the 1S and I have loaded the Xiaomi DaFang bootloader, but cant get the cam online. First time trying this, so dont really know where to begin. It seems to me that there might be a drive issue? Any tips? 

Logfile:
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 0
   id=0 ssid='S&M'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211: Remove monitor interface: refcount=0
netlink: Operstate: ifindex=0 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
Could not read interface wlan0 flags: No such device
nl80211: Set mode ifindex 0 iftype 2 (STATION)
nl80211: Failed to set interface 0 to mode 2: -19 (No such device)
wlan0: Failed to initialize driver interface
Failed to add interface wlan0
wlan0: Cancelling scan request
wlan0: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as 
dropbear: 
bftpd: 
Created new certificate for webserver
lighttpd: 
Startup finished!

**Comment by marciogranzotto** [comment]
I have the same problem.

**Comment by marciogranzotto** [comment]
Oops! I've failed to follow this step:
```
3. Copy config/wpa_supplicant.conf.dist to config/wpa_supplicant.conf
```
I've just copy the file without removing `.dist` at the end of the file

All working now!

**Comment by stenkarlsen** [comment]
@marciogranzotto What CFW did you use?

**Comment by jmtatsch** [comment]
@stenkarlsen seems like your wifi driver is not suitable. Maybe there is yet another hardware variant?

**Comment by ashwinvandijk** [comment]
Got the same issue. I used cfw-1.0.bin, and copied the wpa_supplicant.conf, but I got the same log output in startup.log.

**Comment by eddietio** [comment]
Same issue here, used cfw-1.0bin and copied conf file too.
<pre>
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='MYSSID'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x983218
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x983218 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 78:11:dc:6f:6f:93
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: 
Initialized gpios
Determined image sensor model as 
dropbear: 
bftpd: 
Created new certificate for webserver
lighttpd: 
Startup finished!

</pre>

**Comment by johnywar** [comment]
Hi @ashwinvandijk @stenkarlsen 
you have solved the problem? I have same issue, here is my startup.log
`==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='tcp-guest'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x75d218
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x75d218 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 78:11:dc:70:80:2f
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: 
Initialized gpios
Determined image sensor model as 
dropbear: 
bftpd: 
lighttpd: 
Startup finished!`

Many thanks for any answers.

**Comment by stenkarlsen** [comment]
No, still not working.

**Comment by eddietio** [comment]
@johnywar @stenkarlsen Try ssh-ing into the camera regardless
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/704

**Comment by stenkarlsen** [comment]
Well, there is no IP to ssh into. Its not connected to the network..

**Comment by stenkarlsen** [comment]
No, i tried to get it to connect to the wifi.

**Comment by johnywar** [comment]
This is just for debugging this issue, I will try and let you know. Same problem here #701 is probably not resolved :(

**Comment by johnywar** [comment]
Hi @EliasKotlyar , after booting the camera does not connect to the wifi. What can i do, please. Boot listing here:

[https://pastebin.com/1pTswBvD](url)

**Comment by johnywar** [comment]
Hi all, @stenkarlsen @ashwinvandijk 
I solved this problem. I repeated the whole process again, step by step as [instructed](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md).
Installation it better with the connected serial line, you see what's going on.

Thanks everyone for support.

**Comment by Dams-38** [comment]
In case some of you struggle with this message still I solved Editing

/etc/init.d/rcS

# Start Network:
MAC=$(grep MAC < /params/config/.product_config | cut -c16-27 | sed 's/\(..\)/\1:/g;s/:$//')
 insmod /lib/modules/$KERNEL_VERSION/rtl8189es.ko rtw_initmac="$MAC" # Uncomment for Dafang
# insmod /lib/modules/$KERNEL_VERSION/rtl8189fs.ko rtw_initmac="$MAC" # Uncomment for XiaoFang s1 && Wyzecam V2
# insmod /lib/modules/$KERNEL_VERSION/mt7601Usta.ko # Uncomment for Sannce

I just uncomment the module loading for Dafang (my cam is a Dafang).

**Comment by RayZhang** [comment]
> Oops! I've failed to follow this step:
> 
> ```
> 3. Copy config/wpa_supplicant.conf.dist to config/wpa_supplicant.conf
> ```
> 
> I've just copy the file without removing `.dist` at the end of the file
> 
> All working now!

It's work for me!

**Comment by Dusty-don** [comment]
3. Copy config/wpa_supplicant.conf.dist to config/wpa_supplicant.conf

I followed the instruction, still i am not able to get through this issue of 

"Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory"

Starup Log is as follows
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as 
dropbear: 
Created new certificate for webserver
lighttpd: 
Startup finished!

wpa_supplicant.config

# For more configuration option please see:
# https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="Dusty_Bolt"
        key_mgmt=WPA-PSK
        psk="Abcdef1234"
}

Anybody has  a definite solution

**Comment by Arkady23** [comment]
Maybe it's the router settings?
And what log should be in case of successful connection?
Did anyone understand what the problem with the connection is?
It was strange for me at all. The first time it took a long time to connect, but it did, but the next times no connection was achieved. Even if you repeat it first, even if you don't, it's no use. Maybe the Chinese are deliberately spoiling the camera, if you leave the factory firmware?

In Russian:
Может дело в настройках маршрутизатора?
А какой лог должен быть при успешном подключении?
Кто-нибудь понял в чем проблема с подключением?
У меня вообще было странно. Первый раз долго но подключилось, но подключилось, а вот следующие разы никакого подключения добиться не удалось. Хоть повторяй сначала, хоть нет — всё без толку. Может это китайцы специально портят камеру, если уходить с заводской прошивки?
