### ISSUE TITLE
integration in Domoticz

### ISSUE THREAD

**Issue by wouterkattenbeld** [EliasKotlyar/Xiaomi-Dafang-Hacks#668]
Hello everybody,

today i received the Xiaomi Dafang camera and succesfully applied the hack,
The only problem i have now is that i cant use the camera in Domoticz.

I can add the camera with /cgi-bin/currentpic.cgi as imgURL and when i click the test connection button i can see the picture.
But then after i add the camera i have no picture in domoticz.

Can someone help me with this?

Thanks in advance

**Comment by DifferentComputers** [comment]
Not a Domoticz user.

To the best of my knowledge, the camera does not actually serve jpgs that any system can just use.

I'm an [Indigo](http://indigodomo.com) user, and I have to use wget to pull the image to the Indigo web server, and I display it from there. Indigo is Python based, so I'm doing this in Python: 

`from PIL import Image
import math
import subprocess
import time

pic_destination = "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoWebServer/foo/bar.jpg"
get_image = subprocess.Popen("wget --user root --password ismart12 --no-check-certificate 192.168.10.66/cgi-bin/currentpic.cgi -O /Library/Application\ Support/Perceptive\ Automation/Indigo\ 7/IndigoWebServer/foo/bar.jpg", shell=True)

#and then, because Indigo won't serve the full sized image across its reflector connection, and without the sleep it tries to optimize the pic before it is entirely there:

Image.open(pic_destination)
time.sleep(2)
saved_pic = Image.open(pic_destination)
#width, height = saved_pic.size
#width = width*.59
#height = height*.59
#saved_pic.resize((int(math.floor(width)), int(math.floor(height))), Image.ANTIALIAS)
saved_pic.save("/Library/Application Support/Perceptive Automation/Indigo 7/IndigoWebServer/foo/bar.jpg", optimize=True)`

I have NO doubt there's a much more elegant way to do this, and I hope someone chimes in with an example.

**Comment by czacha338** [comment]
Hi, in lighttpd.conf.dist you have to disable SSL encryption by commenting this lines:

> # Support letsencrypt SSL cert paths
> # (we don't want to upgrade to SSL nor auth' this path)
> 
> # disable https for domoticz integration
> #$HTTP["url"] !~ "^/.well-known/(.*)" {
> #
> #   auth.backend                = "htdigest"
> #    auth.backend.htdigest.userfile = "/system/sdcard/config/lighttpd.user"
> #    auth.require = ( "/" => ("method" => "basic", "realm" => "all", "require" => "user=root"))
> #
> #    $HTTP["scheme"] == "http" {
> #        # capture vhost name with regex conditiona -> %0 in redirect pattern
> #        # must be the most inner block to the redirect rule
> #        $HTTP["host"] =~ ".*" {
> #            url.redirect = (".*" => "https://%0$0")
> #       }
> #    }
> #}

Then it's working better with domoticz :)

**Comment by loglux** [comment]
Any feedback? I have exactly the same issue in Domoticz

**Comment by deennoo** [comment]
Playing with mqtt Is the best solution. 

With i can : 

Have some position preset 
Have à Pir sensor base on dafang détection
Enable / Disable vidéo server

Just usé nodered and google
