### ISSUE TITLE
Auto Night vision doesnt work until restart

### ISSUE THREAD

**Issue by k1ng440** [EliasKotlyar/Xiaomi-Dafang-Hacks#712]
Hello,
Its seems to be a bug with auto night vision switching, its works when i restart the dafang.

**Comment by k1ng440** [comment]
i can see the IR LED turns on through another camera but still total dark.

Night Vision under RSTP doesn't do anything

**Comment by k1ng440** [comment]
some time it works if i turn on and then turn off IR cut

**Comment by Kingo71** [comment]
Same issue here, IR leds are on but still dark image.
If IR-CUT on is working but with a red dominance during the day.

**Comment by Shaker1978** [comment]
There is a general problem with Auto-Nightvision. It doesn't do anything in my case. Nothing turns on or off automatically. Will this be fixed?

Besides: The auto function SHOULD include 1) switching ON IR and 2) switching OFF IR-CUT, because IR-CUT (as far as I understand this) eliminates all the IR information from the sensor that is present even at daytime. (This leads to a more realistic picture compared to what our eyes see). But at night, when IR-LEDs are turned ON but IR-CUT is active and so IR information is eliminated, it is obvious, that the picture stays dark :)

**Comment by Dopeyr** [comment]
Hi @Shaker1978, which camera do you have? The later dafang models do not have a light sensor. I don't see an issue with 2 early dafang models with a light sensor.

You can view more info https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/676 and https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/332 There's also a PR https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/699 for testing a new method of night detection. You might be able to try some of the suggestions on those issues.

**Comment by Shaker1978** [comment]
Hi @Dopeyr. How can I tell which camera revision I have? After posting I read on and found the method of calling autonight -v to see the output of the ADC (i.e. Analog Digital Converter?) but it showed strange values.
It startet with some 1000, went down to 900 and then suddenly up to 377000 And also 400000, without anything changing in the room. What does this tell you?
I must say, that I didn't turn off the auto night vision before I called autonight -v in the ssh. I will reboot the cam and try again today or tomorrow. I will also try to set different thresholds with -O and -F.

What I read in the other thread - I don't have config/autonight.conf.sw. I don't have any autonight.conf.* at all. But I think I have the latest firmware_mod...

**Comment by pax0707** [comment]
I've just tried on S1.
It doesn't work till I restart auto-night-detection service. After that, it's auto sets everything right, till next light change.
