### ISSUE TITLE
Updating from webinterface is broken

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#754]
Updating from webinterface replaces all the files with 0 byte files. I tried it on two different sd cards.

**Comment by Dopeyr** [comment]
There should be output in /system/sdcard/log/update.log - does that reveal any issues?

**Comment by saipsa** [comment]
Here is the log https://pastebin.com/raw/ERD8YGk1

It seems, all files were forced updated in the last update and it resulted in 0 byte files.

**Comment by Dopeyr** [comment]
Roughly when did you update? Just wondering if it's something to do with the github outage around 22nd/23rd October? See https://status.github.com/messages Just wondering if the files were downloaded as 0 bytes because of the outage.

Is it still happening now? 

For what it's worth, the same problem was likely to occur if you ran the update via SSH as it uses the same script underneath, so this issue isn't just restricted to the web interface.

Regardless, perhaps the autoupdate script can be modified to detect 0 byte files and produce an error.

**Comment by saipsa** [comment]
The problem happened a few weeks ago. I ignored it, attributing it to chance error.I reformatted the card and copied the files from the repo. 


I updated it yesterday and camera failed to boot again, so I thought it is not due to chance error. 

Maybe resource throttling by github based on my ISP? 

Nevertheless, zero byte check should be added in the update script.

**Comment by jmtatsch** [comment]
Would be happy to accept a PR

**Comment by saipsa** [comment]
Sure. I will create it in a day or two.

**Comment by columbusgeek** [comment]
This happened to me last night too after pressing update and walking away for the night.  I thought I just had a dropped connection or something.  When I eyeballed the sdcard today I noticed the 0 byte files.   
Easy enough fix, just thought you'd like to know it happened to me as well.

**Comment by saipsa** [comment]
@jmtatsch I have created a PR
