### ISSUE TITLE
path to recorded  video folder in config.json

### ISSUE THREAD

**Issue by Open-Elec-RU** [EliasKotlyar/Xiaomi-Dafang-Hacks#779]
/system/sdcard/videofoldername does not work giving this error in homebridge output:
[11/5/2018, 5:31:58 AM] [Dafang] Checking Recordings Folder Size : /system/sdcard/video/
[11/5/2018, 5:31:58 AM] [Dafang] Error Occurred
[11/5/2018, 5:31:58 AM] [Dafang] { [Error: ENOENT: no such file or directory, lstat '/system/sdcard/video']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/system/sdcard/video' }
the folder is on the sdcard, created manually on a mac.

**Comment by sahilchaddha** [comment]
Hi @Open-Elec-RU , I would advice you to create this issue on the plugin repository.
This repository is only for Xiaomi Dafang Bootloader and CFW. 

The plugin saves the recording on your homebridge running instance and not your camera.
You need to provide a path to your local folder on your Mac instead of camera.
For e.g. Your Folder should look like `/Users/Mac/Downloads/Recordings/`

Make sure your folder exists and have permission to read/write files.

**Comment by Open-Elec-RU** [comment]
Makes sense now, thanks
