### ISSUE TITLE
IR Led problem

### ISSUE THREAD

**Issue by netRunner0** [EliasKotlyar/Xiaomi-Dafang-Hacks#808]
I have 2 cameras of 3 versions, but on the same camera the night light comes on with its life.

At first, the whole picture was purple-tinted; the backlight did not work at all.

Then there was a purple tinge, but it illuminated the whole room.

Now without purple, but the subgrid works at 20-30cm.

How to fix it?

**Comment by chisht** [comment]
@netRunner0 , I'm guessing this is happening everytime it switches between day/night mode? Does it?

Are you using the hardware or software way of autonight?

**Comment by aregbee** [comment]
I am having similar problems with my Wyze Pan (v3 w/HD bootloader).

If I only I turn on the LED's, the entire screen has a purple tint. If I only turn on RTSP Night Vision, what appears to be a greyscale filter is applied on top of the image.

The only way I was able to get the correct effect is if I turn both IR LED & RTSP Night Vision on/off at the same time. From what I could tell, IR LED turns the IR LED's on/off (which has a purple tint), and RTSP Night Vision creates some sort of greyscale filter over top of the image? Could you please clarify whether this is the correct behavior/usage for night vision?

I ask because I am currently creating a more advanced custom vendor file for tinycam and I can only seem to get one effect (IR or Night Vision) to respond. I've tried adding both to the URL, but because both are issued with "cmd=", only one seems to get issued.

Any thoughts?

**Comment by netRunner0** [comment]
The problem was in the jammed shutter. Can close

**Comment by mikeage** [comment]
> The problem was in the jammed shutter. Can close

Wouldn't it be more accurate to say "can't close" in that case? ;-)

**Comment by brkoglu** [comment]
I had the same problem. I resolved it with switching the Video format from SMART to VBR
