### ISSUE TITLE
Autonight mode failure 

### ISSUE THREAD

**Issue by bachoo786** [EliasKotlyar/Xiaomi-Dafang-Hacks#845]
so I updated to the latest software i.e. dafang hacks and what I discover is the auto night mode doesnt not operate correctly. When I turn the lights on from dark the night mode is still turned on and doesnt turn off and if I turn the lights off the night mode doesnt not turned on automatically if it was off.

Does anyone experience this issue with the latest update?

Please help. 

Thanks.

**Comment by saipsa** [comment]
The process is being killed. When I open the sw night configuration in the web interface it switches the mode.

**Comment by bachoo786** [comment]
I can manually turn it on and off via mqtt but it's not automated as advertised

**Comment by bachoo786** [comment]
I am using the Xiaomi dafang 

I have got my autonight.conf enabled but still same problem.

**Comment by jmtatsch** [comment]
You need to specifically enable software autonight with a flag.

**Comment by ortegafernando** [comment]
I can say that software autonight mode works, but I have an issue, sometimes when the sun is leaving, or rissing, I can hear the xiaomi dafang putting on and off quickly (every 2 or 3 seconds) the IR CUT click.
Is there anyway to log this events so I could try to find what is the autonightmode's paramater that is changing a lot so it puts on and off continuosly the IR cut ?

Thanks

**Comment by SomebodySysop** [comment]
I have Xiaofang 1S T20 cameras (as well as a WyzeCam V2) on 2018-12-22T13:53:10Z commit.  On the Xiaofangs, auto night mode is working.  These supposedly have the night vision sensor, but I still have Auto Night Mode "On" with "SW" selected and number of measurements = 4 (I actually don't know what that means, but it works.)

I went to "SW Night configuration" menu, turned "Auto Night Detection" off under "Camera Controls", then clicked "Save" to save the default configuration.  This should create an "autonight.conf" file in /system/sdcard/config on your SD card.

Now, from here you should be able to reboot and auto night should be working.

However, I read this issue: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/740#issuecomment-432793179  And, additionally made this modification to /system/sdcard/scripts/common_functions.sh.

I rebooted and auto night mode has been working fine since.

I do not know if the common_functions.sh modification is necessary.  Probably not, but that's what I did.

**Comment by chisht** [comment]
There is no magic setting for software autonight. Each case is different. That is the reason why we have a SW night configuration page. Those who are having trouble with software autonight, can you please disable the service. Then run the SW night configuration page. And tweak the parameters to see if you can make it to work. Once you get them correct, you can save the settings from the web interface and re-enable the service.

And if it still does not work, please copy and paste the commandline from SW night configuration page. Add -vv to the command line and run it manually from the shell prompt and share the output.

**Comment by ortegafernando** [comment]
I will try, thanks.
