### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by Snotmann** [EliasKotlyar/Xiaomi-Dafang-Hacks#877]
Hey guys,

i want to know how to disable logging as this needs much performace and sd card space.

Regards,
Snot

**Comment by eivinn** [comment]
I've run into this issue. The device stops working after a week or so because the logging fills up /tmp to 100%.
In addition to changing the config of lighttpd I've altered LOGPATH in vi /system/sdcard/controlscripts/rtsp-h264 to /dev/null as well. Will see how this works. If it does logging could be moved to the logfile.

Is there a logrotate script or equivalent that should have been active?

**Comment by joshuakoh7** [comment]
Having the same problem as well. Would like to implement a native logrotate if possible

**Comment by NikZak** [comment]
I would suggest emptying the most space-consuming log every day leaving just some last lines (in the below example 300 lines) for information
```
echo 'tail -n 300 /tmp/lighttpd-access.log > /tmp/lighttpd-access.log' > /system/sdcard/config/cron/periodic/daily/truncate_
log.sh
chmod u+x /system/sdcard/config/cron/periodic/daily/truncate_log.sh
```
