### ISSUE TITLE
Increasing sensitivity of motion detection?

### ISSUE THREAD

**Issue by sepodele** [EliasKotlyar/Xiaomi-Dafang-Hacks#881]
I've configured a very small boundary for motion detection [(356,375) , (404,443)] that isn't triggered when  the pixels go from black to white and vice versa (when lights turn on or off in the street). I saw in another issue that we can't set the sensitivity higher than 4 (Very High) since the motion detection is built in on the camera and not software, but is there a way I can increase chances of it detecting motion when light changes? Would it help to make the boundary even smaller? Like one pixel? Or perhaps change to lower or higher resolution? Any ideas?

**Comment by int2018** [comment]
Hi,
I don't use the camera in this way so I don't have a solution for your question. 
But since you asked also for "any ideas" you might want try to setup a different computer running 'motion'. The software uses the stream of (almost) any IP camera and comes with a good motion detection. I am running it on a raspberry with the p camera and 3 network cameras. It works very good since several years. 
However, I think there is no way to limit the motion detection to a certain rectangle, maybe it works but I don't know. The motion threshold can be configured as a number of changed pixel in the image. I have one camera configured where a rectangle is drawn in the image around the area where the motion was detected. In this way I see that the street lights going off caused the motion detection to fire.
So, it is possible :-)

I don't know what the latest version is, you can check out the github project:
https://motion-project.github.io/motion_config.html#basic_setup_network
