### ISSUE TITLE
Reverting U-Boot to Wyze firmware?

### ISSUE THREAD

**Issue by FuzzyMistborn** [EliasKotlyar/Xiaomi-Dafang-Hacks#948]
I asked in the Gitter chat but didn't get a response.

With Wyze coming out with RTSP in their own software, I'd be curious to test it out when released.  However, I've flashed the open source u-boot (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md).

My question/issue is, is there a way to go back to the stock u-boot so I can run the Wyze firmware again or is that not even necessary (ie I can load the Wyze firmware again without issue).

**Comment by seb62085** [comment]
also wondering if possible

**Comment by reclaimer5146** [comment]
> I can confirm, i flashed everything back to stock Wyze firmware.
> 
> Flashed latest firmware as per these instructions:
> https://support.wyzecam.com/hc/en-us/articles/360009490871-Camera-firmware-flashing-instructions
> 
> Then did a factory reset as per here:
> https://support.wyzecam.com/hc/en-us/articles/360014440692-Factory-reset
> 
> After all this i formatted SD card with nothing on it for local storage.
> not sure if any of these steps are needed... but works for me.

I tried doing this and it didn't work. I tried using DD, but ended up bricking the device and had to unsolder, flash, and resolder the EEPROM. I can flash the dafang-hacks cfw and Dafang will come back up fully functional.

After flashing the official firmware the device comes up, and starts flashing blue and orange. No audio comes from the speaker, but the SoC gets VERY hot. It doesn't get as hot when using Dafang cfw. I have it open since I had to reflash the EEPROM.

So I can continue to use Dafang, but I just can't get it to flash the official firmware and come online. Anything I can gather to assist?

**Comment by MapGuy11** [comment]
I just fixed your issue just flash the uboot from the original firmware folder and mine came back to life.

**Comment by bliteknight** [comment]
Ditto to what @MapGuy11 said. 

Just grab the original uboot.bin for your device in the original firmware folder (the > 2 years one), then follow the uboot flashing instructions here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

I had to then update to the latest firmware before I could connect via the app.
