### ISSUE TITLE
telegram_alert_type=video

### ISSUE THREAD

**Issue by Wibias** [EliasKotlyar/Xiaomi-Dafang-Hacks#957]
So how does "telegram_alert_type=video" work? It doesn't send a **video** to my telegram. But when I do **image** instead of **video** as the alert type it works and it sends an **image** to my telegram!

Is there anything else you have to do to make it work?

**Comment by jmtatsch** [comment]
The videos currently produced don't seem to be compatible with telegram for some reason. maybe you can play around with different formats, hopefully something works.

**Comment by Wibias** [comment]
Normally I would try to fix it myself first. But I have 0 experience with telegram. Only things I found online is this:

```
Video dimensions must be set to 480x320 (320x480 for vertical videos).
H.264 and MPEG-4 should be used as the codec and container.
```

And this:

```
ffmpeg -i input -an -c:v libx264 -crf 26 -vf scale=640:-1 out.mp4
curl -v -F chat_id=CHATID -F video=@out.mp4 -F caption=foobar https://api.telegram.org/bot<TOKEN>/sendVideo
```

Also this:

```
If you upload a video file from computer, in the case the file exceeds 10 MB it will be marked as a file and will not be playable by Web app or Android app. It still will be playable on iPhone however. Bitrate and resolution don't make any difference in that specific case.
```

Not sure if anything of this is usefull. But it would be awesome if it would work out.

**Comment by netRunner0** [comment]
??

**Comment by netRunner0** [comment]
How does it work? I have specified the video option but nothing comes

**Comment by CalumOchkas** [comment]
Worth reviving this? - would be super helpful! I'll try do some work on it when I have a moment

**Comment by eversf** [comment]
I managed to get it working by modifying the /system/sdcard/scripts/detectionOn.sh file as follows:

elif [ "$telegram_alert_type" = "video" ] ; then
		debug_msg "Send telegram video"
		/system/sdcard/bin/avconv -i "$video_tempfile" -s 480x320 "${video_tempfile}-lo.mp4"
		/system/sdcard/bin/telegram v "${video_tempfile}-lo.mp4"
		rm "${video_tempfile}-lo.mp4"

**Comment by netRunner0** [comment]
@eversf 
Come, photo marked GIF.
How to make a video?

**Comment by eversf** [comment]
@netRunner0 Telegram seems to be converting videos to GIF. I'll check later if it supports attachments of any kind but I doubt it will show a preview.

**Comment by jmtatsch** [comment]
@eversf Wow that's it! Thanks a million!
Scaling down is not even necessary for the preview to work.
I wonder why re-encoding is necessary at all?

**Comment by netRunner0** [comment]
Photo come! no animation

**Comment by jmtatsch** [comment]
Did you update to the current version?
Did you set telegram_alert_type=video in your config?
In which device are you viewing your telegram messages?

**Comment by eversf** [comment]
@jmtatsch I tried the re-encoding for it to work and then ran into avconv not knowing what to convert to. That's when I added the .mp4 extension. Didn't think to try without the re-encoding. Great if it works without because it will shave off several seconds.

**Comment by netRunner0** [comment]
> Did you update to the current version?
> Did you set telegram_alert_type=video in your config?
> In which device are you viewing your telegram messages?

Yes
Yes
iOS

**Comment by jmtatsch** [comment]
@netRunner0 Strange, I can view the animated gifs sent by the camera just fine. 
Takes a while for them to be reencoded and sent though.
 Do you have a Dafang or Xiaofang?

**Comment by jmtatsch** [comment]
@eversf Doesn't work without the reencoding yet but we are one step closer at least.

**Comment by netRunner0** [comment]
@jmtatsch Dafang

**Comment by netRunner0** [comment]
In which file is the image or video for telegrams indicated?

**Comment by jmtatsch** [comment]
@netRunner0 The number of frames is governed by `video_duration=10` in `/system/sdcard/config/motion.conf`

**Comment by Wibias** [comment]
Yea taking about 1 - 2 Minutes to send and is pretty laggy, but it works!

**Comment by netRunner0** [comment]
I do not know what to do already.
Problems started after the last update.
Now the camera is responding to commands in telegrams, and that’s it!
If you enable motion detection, then even photos will not come. At the same time, all motion sensors show activity in the homekit. But there are no notifications in telegrams (not counting the video from 1 frame) that somehow came ...
On command /shot, screenshots come

**Comment by netRunner0** [comment]
No…

**Comment by Wibias** [comment]
Yeaa not sure how this is closed. After some update there are no videos/gifs getting send anymore.

**Comment by jmtatsch** [comment]
Your config is likely outdated. Start from a fresh config.

**Comment by Wibias** [comment]
Could be the reason, but I'm pretty good with keeping up with the configs.
I have also activated the swap file. Here is the config.

```###################################################################
# edit this file and move it to /system/sdcard/config/motion.conf #
###################################################################

# Enable verbose debug messages to stderr
debug_msg_enable=false

# Configure the motion core parameters:

region_of_interest=0,111,1280,720
motion_sensitivity=2
motion_indicator_color=2
motion_timeout=-1
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
publish_mqtt_message=true
publish_mqtt_snapshot=true
send_email=false
send_telegram=true
telegram_alert_type=video
send_matrix=false

# General
group_date_pattern="+%d-%m-%Y"
file_date_pattern="+%d-%m-%Y_%H.%M.%S"
video_duration=15

# Record from RTSP (RTSP H264 must be enabled)
# RTSP is alternative for `record_video` function in `detectionOn.sh` - instead of 1s-getimage gets real video.
video_use_rtsp=true
video_rtsp_w=1280
video_rtsp_h=720
video_rtsp_f=15

# Snapshots
save_snapshot=false
save_snapshot_dir=/system/sdcard/DCIM/motion/stills
save_snapshot_attr="0666"
max_snapshot_days=20

# Videos
save_video=false
save_video_dir=/system/sdcard/DCIM/motion/videos
save_video_attr="0666"
max_video_days=10

# Configure FTP snapshots and videos
ftp_snapshot=false
ftp_video=false
ftp_host="ftp.myserver.net"
ftp_port=21
ftp_username="user1"
ftp_password="password2"
ftp_stills_dir="motion/stills"
ftp_videos_dir="motion/videos"

# Configure SMB snapshots and videos
smb_snapshot=false
smb_video=false
smb_share="//DEVICE/SHARE"
smb_username="admin"
smb_password="admin"
smb_stills_path="dafang_camera/stills"
smb_videos_path="dafang_camera/videos"
```

As I said that video sending script worked before. It was actually sending clips of the detected motion. Last time it was working for me was the 11th of November. Also I am using the full video not the gif that was send without "video_use_rtsp=true".

**Comment by Wibias** [comment]
Thought so. Also since I am not the only one with this problem..

**Comment by directional-star** [comment]
@Wibias  - did you find a fix for this issue?

**Comment by Wibias** [comment]
Yea for me it sends video again after changing the dns server of the camera over ssh. (etc/resolv.conf)

**Comment by ex725** [comment]
> Yea for me it sends video again after changing the dns server of the camera over ssh. (etc/resolv.conf)

can you explain more
how did you solve the problem

**Comment by Wibias** [comment]
Connect to the camera over ssh. Write 'vi /etc/resolv.conf' and do your changes to the nameserver there.

**Comment by ex725** [comment]
> Connect to the camera over ssh. Write 'vi /etc/resolv.conf' and do your changes to the nameserver there.

![image](https://user-images.githubusercontent.com/56446241/76251589-4d322f00-6258-11ea-8b6d-ea7a33473602.png)

the file was like this.
did not work anyway

**Comment by Combie81** [comment]
Have you got a static IP set if not resolv.conf is ignored:

## An example resolv.conf to use with static IP configuration
## This file is only relevant when a static address is configured
## Otherwise, resolv.conf is managed by DHCP
## Uncomment lines as needed, everything is optional

**Comment by josep-100** [comment]
I did a few test with trying to get Telegram video alerts to work. 
I did not fully solve the problem, but I am sharing some observations in case it helps.

The key files are config/motion.conf and scripts/detectionOn.sh.

In **motion.conf:** the key parameters are:
```
motion_detection=on
send_telegram=true
telegram_alert_type=video
video_use_rtsp=false
```
The video_use_rtsp is quite important as it determines which type of video gets generated.

When video_use_rtsp = true, the detectionOn.sh script will grab a few seconds from the RTSP server and send it as video to Telegram.
As mentioned on the comments on detectionOn.sh, this method does not always produce a clean video. There are some glitches, or freezes from time to time, probably due to CPU bottlenecks. Also, Telegram (on Android at least) does not run the preview or the video well. 


Hence, my choice has been to set video_use_rtsp= false.
With this setting, detectionOn.sh captures several images with getimage and sticks them together to create a video file.

The original code is as follows:
```
   else
            # Use avconv to stitch multiple JPEGs into 1fps video.
            # I couldn't get it working another way.
            # /dev/videoX inputs fail.
            # Localhost rtsp takes very long (10+ seconds) to start streaming and gets flaky when when memory or cpu are pegged.
            # This is a clungy method, but works well even at high res, fps, cpu, and memory load!
            ( while [ "$(/system/sdcard/bin/busybox date "+%s")" -le "$(/system/sdcard/bin/busybox expr "$(/system/sdcard/bin/busybox stat -c "%X" /run/recording_video.flock)" + "$video_duration")" ]; do
                    /system/sdcard/bin/getimage
                    sleep 1
                done ) | /system/sdcard/bin/avconv -analyzeduration 0 -f image2pipe -r 1 -c:v mjpeg -c:a none -i - -c:v copy -c:a none -f mp4 -y "$video_tempfile"
        fi
```
The video generated with the above, works well as preview in Telegram Android, and Telegram iOS, but gets frozen when I open the file received.  The other issue is that it takes quite long to generate, 1m30 or 2min between movement detection and delivery to Telegram.
Another issue is that the frames are 1 second apart, which is too much for me, and there is no audio. 

I modified the code to capture more frames per second, I settled with an image every 0.4 seconds (with sleep 0.4), and a slightly modified frame rate on the file (as indicated by the -r XX parameter in avconv). 

The following is the code I used at the end:

```
        else
            # Use avconv to stitch multiple JPEGs into 1fps video.
            # I couldn't get it working another way.
            # /dev/videoX inputs fail.
            # Localhost rtsp takes very long (10+ seconds) to start streaming and gets flaky when when memory or cpu are pegged.
            # This is a clungy method, but works well even at high res, fps, cpu, and memory load!
            ( while [ "$(/system/sdcard/bin/busybox date "+%s")" -le "$(/system/sdcard/bin/busybox expr "$(/system/sdcard/bin/busybox stat -c "%X" /run/recording_video.flock)" + "$video_duration")" ]; do
                    /system/sdcard/bin/getimage
					
#JF: Next line determines how many images are used to compose the video. Initially, it was 'sleep 1' which means take a snapshot every 1 second. 
# It can be changed to sleep 0.5 or sleep 0.2 or similar, to generate 2 fps or 5 fps. 
# In the line below, the parameter -r XX should be the corresponding one, if sleep is 0.2, that is 5fps and should be -r 5
# The challenge is that higher number of images requires more cpu on the camera for processing. Eg. I tested and it takes 2m30 aprox for a sleep 0.2 to generate and send the telegram video
# 
                    sleep 0.4
                done ) | /system/sdcard/bin/avconv -analyzeduration 0 -f image2pipe -r 3 -c:v mjpeg -c:a none -i - -c:v copy -c:a none -f mp4 -y "$video_tempfile"
        fi
```

Finally, another relevant piece of code is when the video_tempfile generated above, after movement detection, is converted to a suitable format and sent to Telegram.

What I did is change the avconv line and add parameters to set the output size (-s 1920x1080), the file format (-f mp4) and the target bitrate (-b:v 2500k):

```
elif [ "$telegram_alert_type" = "video" ] ; then
		debug_msg "Send telegram video"
		if [ "$video_use_rtsp" = true ]; then
			/system/sdcard/bin/telegram v "$video_tempfile"
        	else
## JF
#Note: -b:v XXX sets the target bitrate. For me 2500K works well and generates videos that Telegram plays nicely
			/system/sdcard/bin/avconv -i "$video_tempfile" -s 1920x1080 -f mp4 -b:v 2500k "$video_tempfile-lo.mp4"
			/system/sdcard/bin/telegram v "$video_tempfile-lo.mp4"
			rm "$video_tempfile-lo.mp4"
		fi
```
I found that the '-f mp4' is key for Telegram to accept the videos as valid. The size parameter (-s 1920x1080) is only there to make sure the image quality is not degraded, same with -b:v 2500k. I tried several bitrates and below 2000K I seem to notice artifacts on the video.

I have not understood what makes a Telegram video fully compatible. I read online that video dimensions must be set to 480x320 (320x480 for vertical videos). H. 264 and MPEG-4, however after multiple trial-and-error, I could not find any clear patterns. 

Sometimes the video preview works but opening the video on Telegram does not, sometimes it works on Android but not on iOS.

After multiple tests, I settled for the modifications above, both on the video generation, and sending to Telegram.
This works on my Android and on iOS. The whole process takes about 2 minutes from motion detection to receiving the video on Telegram on my NEOS Smartcam 2. I guess better CPUs would produce better results.

Areas for improvement:
- The code used to generate the video file when video_use_rtsp=false, based on stitching multiple images, uses /bin/getimage for the captures. I found getimage does not get a high image resolution. I did not find any parameters on getimage and not expert enough to modify the code. Would be a great improvement to get high res pictures.

- The method of stitching images is a bit slow, but at least generates a playable video, which is great.
