### ISSUE TITLE
Xiaofang 1s custom bootloader uEnv

### ISSUE THREAD

**Issue by EsEnZeT** [EliasKotlyar/Xiaomi-Dafang-Hacks#963]
Hi,

so I confirmed my device is 64mb (unfortunately), flashed custom uboot v2 ( https://github.com/Dafang-Hacks/uboot/blob/master/compiled_bootloader/xiaofang1s_64mb_v2.bin )

and changed uEnv.bootfromnand.txt to uEnv.txt - didn't boot because looks like mem values are not for that cam.

So I've changed them to default for that model:
`console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)`

then booted correctly + confirmed custom bootloader is there `U-Boot 2013.07-g4401361-dirty (Jul 24 2018 - 00:13:48)`

My question is regarding the cmdline (uEnv) memory values:
- is the approach I took correct?
- should I manipulate further the mem ispmem rmem values?

**Comment by dsbaars** [comment]
It did not boot after you changed uEnv.bootfromnand.txt to uEnv.txt, since it needs to start from SD card. I think this instruction is only included to verify correct working of the bootloader (it should turn blue, since uEnv.txt is there).

What do you want to boot? If you want to use the image where you need to copy everything from "firmware_mod", you don't need to have a custom uEnv.txt. The custom bootloader adds support for booting from an ext3 partition from the microsd card [more about that here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_sdcard.md).

Note that if you use https://github.com/Dafang-Hacks/rootfs as your filesystem, you need to uncomment the correct line (59) in [etc/init.d/rcS](https://github.com/Dafang-Hacks/rootfs/blob/master/etc/init.d/rcS#L59)

With that, I got it to boot but I got stuck at getting image from the sensor.

**Comment by jmtatsch** [comment]
@dsbaars try https://github.com/anmaped/openfang Wyze Cam V2 likely uses the same image sensor.

**Comment by dsbaars** [comment]
> @dsbaars try https://github.com/anmaped/openfang Wyze Cam V2 likely uses the same image sensor.

Thanks, unfortunately the latest release (on the releases) does not seem to work as well. It does boot and I can connect to the webinterface, but when starting v4l2rtspserver (as root, using SSH) I get a similar error as https://github.com/anmaped/openfang/issues/13. 

I'm now trying to build openfang from the referred commit (73bd1cf), since building the master resulted in a non-working image (it does seem to boot, i get a solid orange led but it doesn't connect to my WiFi).

When trying to build 73bd1cf it keeps complaining about a non-working patch for v4l2rtspserver 0.1.3...

**Comment by EsEnZeT** [comment]
Thanks all, it's more clear now
