### ISSUE TITLE
Please add MIT license

### ISSUE THREAD

**Issue by Chedberg84** [EliasKotlyar/Xiaomi-Dafang-Hacks#974]
Can you please add an MIT license to this repository. I'm not sure if you are aware but people don't have rights to use the software unless an open source license is present.

You may not be aware of this, but legally, without a license, no one can use your code.

http://opensource.stackexchange.com/q/1720/775

**Comment by saipsa** [comment]
GPL v3 is more appropirate

**Comment by jmtatsch** [comment]
@EliasKotlyar which one would you prefer?

**Comment by Chedberg84** [comment]
Here is some further information around licensing. 
https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

I would always prefer the MIT license since it enables the largest amount of people to use your software. 
It's the "Hey, this software is free, and you aren't going to run into legal restrictions, why not try it out" license.

**Comment by jmtatsch** [comment]
I generally prefer the “I open sourced my code so you should too” way, but it should be up to Elias to decide ...

**Comment by EliasKotlyar** [comment]
Hello everyone,

Sorry, but i cannot "decide" that. We are basically using a lot of code, which is belonging to Ingenic. They somehow licensed it(or maybe not, i am not sure), and provided it under an NDA to someone, who leaked it. We are using this "leaked" version of SDK, and created a lot of software around that. It is not a safe situation to release our software under any kind of license.  I am in contact with someone, who has relationsships with Ingenic, to resolve this situation, but it may take a lot of time and understanding, that we are doing it for free and open-source. 

Legally speaking: I am pretty sure that we are not making anything wrong right now, because the Ingenic SDK has never been released in anywhere except of china. China has a really liberal copyright - as far as i know. There are no other jurisdictions which we need to address. To be sure, we need to ask Ingenic for permission of releasing software around their SDK. If they ask us to remove that, we will need to do that. But i suppose that they are okey with our hobby project.
